<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ConversationMessage.proto

namespace ConversationMessage\NestedMessage;

use UnexpectedValueException;

/**
 * Protobuf type <code>ConversationMessage.NestedMessage.NestedMessageType</code>
 */
class NestedMessageType
{
    /**
     * Generated from protobuf enum <code>Quote = 0;</code>
     */
    const Quote = 0;
    /**
     * Generated from protobuf enum <code>Forward = 1;</code>
     */
    const Forward = 1;

    private static $valueToName = [
        self::Quote => 'Quote',
        self::Forward => 'Forward',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NestedMessageType::class, \ConversationMessage_NestedMessage_NestedMessageType::class);

