<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/UserData.proto

namespace UserData;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>UserData.BotInfo</code>
 */
class BotInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool canReceiveMessages = 1;</code>
     */
    private $canReceiveMessages = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $canReceiveMessages
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserData\UserData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool canReceiveMessages = 1;</code>
     * @return bool
     */
    public function getCanReceiveMessages()
    {
        return $this->canReceiveMessages;
    }

    /**
     * Generated from protobuf field <code>bool canReceiveMessages = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanReceiveMessages($var)
    {
        GPBUtil::checkBool($var);
        $this->canReceiveMessages = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BotInfo::class, \UserData_BotInfo::class);

