<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ArchiveConversation.proto

namespace GPBMetadata\Messenger;

class ArchiveConversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a570a234d657373656e6765722f41726368697665436f6e766572736174" .
            "696f6e2e70726f746f22280a1341726368697665436f6e76657273617469" .
            "6f6e12110a096d6573736167654964180120012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

