<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ArchiveConversationStatusResponse.proto

namespace GPBMetadata\Messenger;

class ArchiveConversationStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad2010a314d657373656e6765722f41726368697665436f6e7665727361" .
            "74696f6e537461747573526573706f6e73652e70726f746f2294010a2141" .
            "726368697665436f6e766572736174696f6e537461747573526573706f6e" .
            "736512390a0673746174757318012001280e32292e41726368697665436f" .
            "6e766572736174696f6e537461747573526573706f6e73652e5374617475" .
            "7312160a0e636f6e766572736174696f6e4964180220012803221c0a0653" .
            "746174757312060a024f4b1000120a0a064641494c45441001620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

