<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ChangeIgnoreStateStatusResponse.proto

namespace GPBMetadata\Messenger;

class ChangeIgnoreStateStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7010a2f4d657373656e6765722f4368616e676549676e6f7265537461" .
            "7465537461747573526573706f6e73652e70726f746f22bb010a1f436861" .
            "6e676549676e6f72655374617465537461747573526573706f6e73651237" .
            "0a0673746174757318012001280e32272e4368616e676549676e6f726553" .
            "74617465537461747573526573706f6e73652e537461747573120e0a0661" .
            "6374696f6e180220012805120e0a06757365724964180320012805223f0a" .
            "0653746174757312060a024f4b1000120d0a094e4f5f4348414e47451001" .
            "12120a0e50524f5445435445445f555345521002120a0a064641494c4544" .
            "1003620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

