<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ChangeIgnoreState.proto

namespace GPBMetadata\Messenger;

class ChangeIgnoreState
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messenger\IgnoreStateAction::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a740a214d657373656e6765722f4368616e676549676e6f726553746174" .
            "652e70726f746f22470a114368616e676549676e6f72655374617465120e" .
            "0a0675736572496418012001280512220a06616374696f6e18022001280e" .
            "32122e49676e6f72655374617465416374696f6e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

