<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ClientSettingsUpdatedEvent.proto

namespace GPBMetadata\Messenger;

class ClientSettingsUpdatedEvent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messenger\ClientSettings::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a750a2a4d657373656e6765722f436c69656e7453657474696e67735570" .
            "64617465644576656e742e70726f746f223f0a1a436c69656e7453657474" .
            "696e6773557064617465644576656e7412210a0873657474696e67731801" .
            "2001280b320f2e436c69656e7453657474696e6773620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

