<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ContactList.proto

namespace GPBMetadata\Messenger;

class ContactList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a450a1b4d657373656e6765722f436f6e746163744c6973742e70726f74" .
            "6f221e0a0b436f6e746163744c697374120f0a0775736572496473180120" .
            "032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

