<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ConversationSnapStatus.proto

namespace GPBMetadata\Messenger;

class ConversationSnapStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a264d657373656e6765722f436f6e766572736174696f6e536e61" .
            "705374617475732e70726f746f2a790a16436f6e766572736174696f6e53" .
            "6e617053746174757312100a0c4e6f74417661696c61626c651000120d0a" .
            "09556e64656369646564100112070a03596573100212060a024e6f100312" .
            "150a08466972737454727910ffffffffffffffffff0112160a095365636f" .
            "6e6454727910feffffffffffffffff01620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

