<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ConversationList.proto

namespace GPBMetadata\Messenger;

class ConversationList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messenger\Conversation::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a204d657373656e6765722f436f6e766572736174696f6e4c697374" .
            "2e70726f746f22380a10436f6e766572736174696f6e4c69737412240a0d" .
            "636f6e766572736174696f6e7318012003280b320d2e436f6e7665727361" .
            "74696f6e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

