<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/Conversation.proto

namespace GPBMetadata\Messenger;

class Conversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messenger\ConversationMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c020a1c4d657373656e6765722f436f6e766572736174696f6e2e7072" .
            "6f746f22f3010a0c436f6e766572736174696f6e121b0a13757064617465" .
            "5265616454696d657374616d7018012001280812140a0c70617274696369" .
            "70616e747318022003280512260a086d6573736167657318032003280b32" .
            "142e436f6e766572736174696f6e4d65737361676512140a0c6172636869" .
            "7665496e64657818042001280312130a0b64656c657465496e6465781805" .
            "2001280312150a0d6c61737452656164496e64657818062001280312160a" .
            "0e636f6e766572736174696f6e4964180720012803121a0a12756e726561" .
            "644d657373616765436f756e7418082001280512120a0a736e6170537461" .
            "747573180920012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

