<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ForwardMessage.proto

namespace GPBMetadata\Messenger;

class ForwardMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a690a1e4d657373656e6765722f466f72776172644d6573736167652e70" .
            "726f746f223f0a0e466f72776172644d65737361676512110a0972656365" .
            "6976657273180120032805121a0a12666f727761726465644d6573736167" .
            "654964180220012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

