<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/GetClientSettingsRequest.proto

namespace GPBMetadata\Messenger;

class GetClientSettingsRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4e0a284d657373656e6765722f476574436c69656e7453657474696e67" .
            "73526571756573742e70726f746f221a0a18476574436c69656e74536574" .
            "74696e677352657175657374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

