<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/MessageSendError.proto

namespace GPBMetadata\Messenger;

class MessageSendError
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6010a204d657373656e6765722f4d65737361676553656e644572726f" .
            "722e70726f746f227a0a104d65737361676553656e644572726f72122b0a" .
            "06726561736f6e18012001280e321b2e4d65737361676553656e64457272" .
            "6f722e4572726f7254797065120c0a0474657874180220012809222b0a09" .
            "4572726f725479706512130a0f4e69636b6e616d65496e76616c69641000" .
            "12090a054f746865721001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

