<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/MessageStatus.proto

namespace GPBMetadata\Messenger;

class MessageStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a010a1d4d657373656e6765722f4d6573736167655374617475732e70" .
            "726f746f22710a0d4d65737361676553746174757312250a067374617475" .
            "7318012001280e32152e4d6573736167655374617475732e537461747573" .
            "12110a096d657373616765496418022001280322260a0653746174757312" .
            "080a0453656e74100012120a0e5365727665725265636569766564100162" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

