<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/QuoteMessage.proto

namespace GPBMetadata\Messenger;

class QuoteMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7010a1c4d657373656e6765722f51756f74654d6573736167652e7072" .
            "6f746f227f0a0c51756f74654d65737361676512110a0972656365697665" .
            "7273180120032805120c0a0474657874180220012809120f0a0771756f74" .
            "65496418032001280312210a19697351756f74654f66466f727761726465" .
            "644d657373616765180420012808121a0a12666f727761726465644d6573" .
            "736167654964180520012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

