<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ReadAllConversationsStatusResponse.proto

namespace GPBMetadata\Messenger;

class ReadAllConversationsStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abc010a324d657373656e6765722f52656164416c6c436f6e7665727361" .
            "74696f6e73537461747573526573706f6e73652e70726f746f227e0a2252" .
            "656164416c6c436f6e766572736174696f6e73537461747573526573706f" .
            "6e7365123a0a0673746174757318012001280e322a2e52656164416c6c43" .
            "6f6e766572736174696f6e73537461747573526573706f6e73652e537461" .
            "747573221c0a0653746174757312060a024f4b1000120a0a064641494c45" .
            "441001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

