<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ReadConversation.proto

namespace GPBMetadata\Messenger;

class ReadConversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a560a204d657373656e6765722f52656164436f6e766572736174696f6e" .
            "2e70726f746f222a0a1052656164436f6e766572736174696f6e12160a0e" .
            "636f6e766572736174696f6e4964180120032803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

