<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ReadAllConversations.proto

namespace GPBMetadata\Messenger;

class ReadAllConversations
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5e0a244d657373656e6765722f52656164416c6c436f6e766572736174" .
            "696f6e732e70726f746f222e0a1452656164416c6c436f6e766572736174" .
            "696f6e7312160a0e636f6e766572736174696f6e49641801200328036206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

