<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/RequestConversations.proto

namespace GPBMetadata\Messenger;

class RequestConversations
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a740a244d657373656e6765722f52657175657374436f6e766572736174" .
            "696f6e732e70726f746f22440a1452657175657374436f6e766572736174" .
            "696f6e7312160a0e73696e636554696d657374616d701801200128031214" .
            "0a0c6d6573736167654c696d6974180220012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

