<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/RequestSnapDownload.proto

namespace GPBMetadata\Messenger;

class RequestSnapDownload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a234d657373656e6765722f52657175657374536e6170446f776e6c" .
            "6f61642e70726f746f223b0a1352657175657374536e6170446f776e6c6f" .
            "616412110a096d657373616765496418012001280312110a096973507265" .
            "76696577180220012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

