<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/RequestStarredMessages.proto

namespace GPBMetadata\Messenger;

class RequestStarredMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4a0a264d657373656e6765722f52657175657374537461727265644d65" .
            "7373616765732e70726f746f22180a165265717565737453746172726564" .
            "4d65737361676573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

