<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SendMessageToNick.proto

namespace GPBMetadata\Messenger;

class SendMessageToNick
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a610a214d657373656e6765722f53656e644d657373616765546f4e6963" .
            "6b2e70726f746f22340a1153656e644d657373616765546f4e69636b1211" .
            "0a09726563656976657273180120032809120c0a04746578741802200128" .
            "09620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

