<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SendMessageStatusResponse.proto

namespace GPBMetadata\Messenger;

class SendMessageStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe020a294d657373656e6765722f53656e644d65737361676553746174" .
            "7573526573706f6e73652e70726f746f2288020a1953656e644d65737361" .
            "6765537461747573526573706f6e736512310a0673746174757318012001" .
            "280e32212e53656e644d657373616765537461747573526573706f6e7365" .
            "2e53746174757312110a096d657373616765496418022001280312140a0c" .
            "736f7572636555736572496418032001280512160a0e726563697069656e" .
            "74436f756e7418042001280522770a0653746174757312060a024f4b1000" .
            "12140a10494e56414c49445f4e49434b4e414d45100112100a0c49535f4d" .
            "4f44455241544f52100212130a0f504f5354424f585f49535f46554c4c10" .
            "03120c0a0846494c54455245441004120a0a064641494c45441005120e0a" .
            "0a464f52574152445f4f4b1006620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

