<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SendMessage.proto

namespace GPBMetadata\Messenger;

class SendMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a550a1b4d657373656e6765722f53656e644d6573736167652e70726f74" .
            "6f222e0a0b53656e644d65737361676512110a0972656365697665727318" .
            "0120032805120c0a0474657874180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

