<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SendTyping.proto

namespace GPBMetadata\Messenger;

class SendTyping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5d0a1a4d657373656e6765722f53656e64547970696e672e70726f746f" .
            "22370a0a53656e64547970696e6712110a09726563656976657273180120" .
            "03280512160a0e636f6e766572736174696f6e4964180220012803620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

