<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SetClientSettingsRequest.proto

namespace GPBMetadata\Messenger;

class SetClientSettingsRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Messenger\ClientSettings::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a710a284d657373656e6765722f536574436c69656e7453657474696e67" .
            "73526571756573742e70726f746f223d0a18536574436c69656e74536574" .
            "74696e67735265717565737412210a0873657474696e677318012001280b" .
            "320f2e436c69656e7453657474696e6773620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

