<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SetSnapsAllowed.proto

namespace GPBMetadata\Messenger;

class SetSnapsAllowed
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5d0a1f4d657373656e6765722f536574536e617073416c6c6f7765642e" .
            "70726f746f22320a0f536574536e617073416c6c6f776564120e0a067573" .
            "65724964180120012805120f0a07616c6c6f776564180220012808620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

