<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SetTyping.proto

namespace GPBMetadata\Messenger;

class SetTyping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a194d657373656e6765722f536574547970696e672e70726f746f22" .
            "490a09536574547970696e67120e0a067573657249641801200128051214" .
            "0a0c7061727469636970616e747318022003280512160a0e636f6e766572" .
            "736174696f6e4964180320012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

