<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SnapDownloadResponse.proto

namespace GPBMetadata\Messenger;

class SnapDownloadResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac2010a244d657373656e6765722f536e6170446f776e6c6f6164526573" .
            "706f6e73652e70726f746f2291010a14536e6170446f776e6c6f61645265" .
            "73706f6e7365120b0a0375726c18012001280912110a096d657373616765" .
            "4964180220012803120f0a0770686f746f496418032001280312110a0969" .
            "735072657669657718042001280812100a08736e61705479706518052001" .
            "280512100a08696d6167654b657918062001280912110a09657874726154" .
            "696d65180720012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

