<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SnapStatusUpdate.proto

namespace GPBMetadata\Messenger;

class SnapStatusUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a204d657373656e6765722f536e6170537461747573557064617465" .
            "2e70726f746f223e0a10536e617053746174757355706461746512160a0e" .
            "636f6e766572736174696f6e496418012001280312120a0a736e61705374" .
            "61747573180220012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

