<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/StarMessages.proto

namespace GPBMetadata\Messenger;

class StarMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4a0a1c4d657373656e6765722f537461724d657373616765732e70726f" .
            "746f22220a0c537461724d6573736167657312120a0a6d65737361676549" .
            "6473180120032803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

