<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UnArchiveConversation.proto

namespace GPBMetadata\Messenger;

class UnArchiveConversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5b0a254d657373656e6765722f556e41726368697665436f6e76657273" .
            "6174696f6e2e70726f746f222a0a15556e41726368697665436f6e766572" .
            "736174696f6e12110a096d6573736167654964180120012803620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

