<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UnreadConversation.proto

namespace GPBMetadata\Messenger;

class UnreadConversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5a0a224d657373656e6765722f556e72656164436f6e76657273617469" .
            "6f6e2e70726f746f222c0a12556e72656164436f6e766572736174696f6e" .
            "12160a0e636f6e766572736174696f6e4964180120032803620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

