<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UnstarMessages.proto

namespace GPBMetadata\Messenger;

class UnstarMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4e0a1e4d657373656e6765722f556e737461724d657373616765732e70" .
            "726f746f22240a0e556e737461724d6573736167657312120a0a6d657373" .
            "616765496473180120032803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

