<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UpdateConversationArchiveState.proto

namespace GPBMetadata\Messenger;

class UpdateConversationArchiveState
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3010a2e4d657373656e6765722f557064617465436f6e766572736174" .
            "696f6e4172636869766553746174652e70726f746f22a8010a1e55706461" .
            "7465436f6e766572736174696f6e41726368697665537461746512160a0e" .
            "636f6e766572736174696f6e496418012001280312340a05737461746518" .
            "022001280e32252e557064617465436f6e766572736174696f6e41726368" .
            "69766553746174652e537461746512110a096d6573736167654964180320" .
            "01280322250a055374617465120e0a0a556e61726368697665641000120c" .
            "0a0841726368697665641001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

