<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/CannotJoinChannel.proto

namespace GPBMetadata\Channel;

class CannotJoinChannel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf020a1f4368616e6e656c2f43616e6e6f744a6f696e4368616e6e656c" .
            "2e70726f746f2283020a1143616e6e6f744a6f696e4368616e6e656c1225" .
            "0a096368616e6e656c494418012001280b32122e4368616e6e656c496465" .
            "6e74696669657212130a0b6368616e6e656c6e616d651802200128091229" .
            "0a06726561736f6e18032001280b32192e43616e6e6f744a6f696e436861" .
            "6e6e656c2e526561736f6e1a280a06526561736f6e120c0a047479706518" .
            "012001280512100a086672656574657874180220012809225d0a04547970" .
            "65120e0a0a5045524d495353494f4e1000120a0a0642414e4e4544100112" .
            "080a0446554c4c100212100a0c524551554952454d454e5453100312120a" .
            "0e444f45535f4e4f545f4558495354100412090a054f5448455210056206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

