<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelDataRequest.proto

namespace GPBMetadata\Channel;

class ChannelDataRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a770a204368616e6e656c2f4368616e6e656c4461746152657175657374" .
            "2e70726f746f224b0a124368616e6e656c44617461526571756573741225" .
            "0a096368616e6e656c496418012001280b32122e4368616e6e656c496465" .
            "6e746966696572120e0a066669656c6473180220032805620670726f746f" .
            "33"
        ), true);

        static::$is_initialized = true;
    }
}

