<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelDataId.proto

namespace GPBMetadata\Channel;

class ChannelDataId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7010a1b4368616e6e656c2f4368616e6e656c4461746149642e70726f" .
            "746f2a9f010a0d4368616e6e656c44617461496412060a02496410001208" .
            "0a044e616d651001120a0a064d696e4167651002120a0a064d6178416765" .
            "1003120f0a0b4d617843686174746572731004120d0a094170706c657449" .
            "64731005120b0a0756697369626c651006120d0a0955736572436f756e74" .
            "100712130a0f50726576696577496d61676555726c100812130a0f426163" .
            "6b67726f756e64436f6c6f721009620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

