<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelIdentifier.proto

namespace GPBMetadata\Channel;

class ChannelIdentifier
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a1f4368616e6e656c2f4368616e6e656c4964656e7469666965722e" .
            "70726f746f22390a114368616e6e656c4964656e746966696572120e0a06" .
            "726f6f74496418012001280312140a0c7375626368616e6e656c49641802" .
            "20012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

