<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelDataResponse.proto

namespace GPBMetadata\Channel;

class ChannelDataResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a760a214368616e6e656c2f4368616e6e656c44617461526573706f6e73" .
            "652e70726f746f22490a134368616e6e656c44617461526573706f6e7365" .
            "12160a0e726573706f6e7365537461747573180120012805121a0a046461" .
            "746118022001280b320c2e4368616e6e656c44617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

