<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/DisconnectedByLegacyClientConnectEvent.proto

namespace GPBMetadata\Channel;

class DisconnectedByLegacyClientConnectEvent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a780a344368616e6e656c2f446973636f6e6e656374656442794c656761" .
            "6379436c69656e74436f6e6e6563744576656e742e70726f746f22380a26" .
            "446973636f6e6e656374656442794c6567616379436c69656e74436f6e6e" .
            "6563744576656e74120e0a06757365724964180120012804620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

