<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/IgnoreListUpdate.proto

namespace GPBMetadata\Channel;

class IgnoreListUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5c0a1e4368616e6e656c2f49676e6f72654c6973745570646174652e70" .
            "726f746f22320a1049676e6f72654c697374557064617465120e0a067573" .
            "65724944180120012805120e0a06616374696f6e18022001280562067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

