<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/IgnoreListComplete.proto

namespace GPBMetadata\Channel;

class IgnoreListComplete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a510a204368616e6e656c2f49676e6f72654c697374436f6d706c657465" .
            "2e70726f746f22250a1249676e6f72654c697374436f6d706c657465120f" .
            "0a0769676e6f726573180120032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

