<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/InitialChannelJoin.proto

namespace GPBMetadata\Channel;

class InitialChannelJoin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a400a204368616e6e656c2f496e697469616c4368616e6e656c4a6f696e" .
            "2e70726f746f22140a12496e697469616c4368616e6e656c4a6f696e6206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

