<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/JoinChannel.proto

namespace GPBMetadata\Channel;

class JoinChannel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a720a194368616e6e656c2f4a6f696e4368616e6e656c2e70726f746f22" .
            "4d0a0b4a6f696e4368616e6e656c12250a096368616e6e656c4944180120" .
            "01280b32122e4368616e6e656c4964656e74696669657212170a0f616c6c" .
            "6f775375624368616e6e656c180220012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

