<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/JoinChannelByName.proto

namespace GPBMetadata\Channel;

class JoinChannelByName
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6c0a1f4368616e6e656c2f4a6f696e4368616e6e656c42794e616d652e" .
            "70726f746f22410a114a6f696e4368616e6e656c42794e616d6512130a0b" .
            "6368616e6e656c4e616d6518012001280912170a0f616c6c6f7753756243" .
            "68616e6e656c180220012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

