<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/MessageInChannelServer.proto

namespace GPBMetadata\Channel;

class MessageInChannelServer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        \GPBMetadata\Channel\MessageID::initOnce();
        \GPBMetadata\Core\FormattedText::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aba020a244368616e6e656c2f4d657373616765496e4368616e6e656c53" .
            "65727665722e70726f746f1a174368616e6e656c2f4d6573736167654944" .
            "2e70726f746f1a18636f72652f466f726d6174746564546578742e70726f" .
            "746f22d6010a164d657373616765496e4368616e6e656c53657276657212" .
            "250a096368616e6e656c494418012001280b32122e4368616e6e656c4964" .
            "656e74696669657212100a0873656e6465724944180220012805121a0a12" .
            "646570726563617465645f6d657373616765180320012809121f0a076d65" .
            "737361676518072001280b320e2e466f726d61747465645465787412130a" .
            "0b6d65737361676554797065180420012805121d0a096d65737361676549" .
            "4418052001280b320a2e4d657373616765494412120a0a72656365697665" .
            "724944180620032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

