<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/MessageInChannel.proto

namespace GPBMetadata\Channel;

class MessageInChannel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a740a1e4368616e6e656c2f4d657373616765496e4368616e6e656c2e70" .
            "726f746f224a0a104d657373616765496e4368616e6e656c12250a096368" .
            "616e6e656c494418012001280b32122e4368616e6e656c4964656e746966" .
            "696572120f0a076d657373616765180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

