<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/NicklistChange.proto

namespace GPBMetadata\Channel;

class NicklistChange
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\UserNicklistData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a690a1c4368616e6e656c2f4e69636b6c6973744368616e67652e70726f" .
            "746f22410a0e4e69636b6c6973744368616e6765121f0a04757365721801" .
            "2001280b32112e557365724e69636b6c69737444617461120e0a06616374" .
            "696f6e180220012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

