<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/NicklistUpdate.proto

namespace GPBMetadata\Channel;

class NicklistUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        \GPBMetadata\Channel\NicklistChange::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a1c4368616e6e656c2f4e69636b6c6973745570646174652e7072" .
            "6f746f1a1c4368616e6e656c2f4e69636b6c6973744368616e67652e7072" .
            "6f746f226f0a0e4e69636b6c69737455706461746512250a096368616e6e" .
            "656c494418012001280b32122e4368616e6e656c4964656e746966696572" .
            "12150a0d76657273696f6e4e756d626572180220012803121f0a06636861" .
            "6e676518032003280b320f2e4e69636b6c6973744368616e676562067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

