<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/OnlineUsersResponse.proto

namespace GPBMetadata\Channel;

class OnlineUsersResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a530a214368616e6e656c2f4f6e6c696e655573657273526573706f6e73" .
            "652e70726f746f22260a134f6e6c696e655573657273526573706f6e7365" .
            "120f0a0775736572496473180120032803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

