<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/OnlineUsersRequest.proto

namespace GPBMetadata\Channel;

class OnlineUsersRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a670a204368616e6e656c2f4f6e6c696e65557365727352657175657374" .
            "2e70726f746f223b0a124f6e6c696e655573657273526571756573741225" .
            "0a096368616e6e656c496418012001280b32122e4368616e6e656c496465" .
            "6e746966696572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

