<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/PrivateMessageServer.proto

namespace GPBMetadata\Channel;

class PrivateMessageServer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a224368616e6e656c2f507269766174654d65737361676553657276" .
            "65722e70726f746f224d0a14507269766174654d65737361676553657276" .
            "657212100a0873656e646572494418012001280512120a0a726563656976" .
            "65724944180220032805120f0a076d657373616765180320012809620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

