<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/PrivateMessage.proto

namespace GPBMetadata\Channel;

class PrivateMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5c0a1c4368616e6e656c2f507269766174654d6573736167652e70726f" .
            "746f22340a0e507269766174654d65737361676512110a09726563656976" .
            "657273180120032809120f0a076d65737361676518022001280962067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

