<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/RequestIgnoreList.proto

namespace GPBMetadata\Channel;

class RequestIgnoreList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a3e0a1f4368616e6e656c2f5265717565737449676e6f72654c6973742e" .
            "70726f746f22130a115265717565737449676e6f72654c69737462067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

