<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/RequestNicklistIntern.proto

namespace GPBMetadata\Channel;

class RequestNicklistIntern
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6d0a234368616e6e656c2f526571756573744e69636b6c697374496e74" .
            "65726e2e70726f746f223e0a15526571756573744e69636b6c697374496e" .
            "7465726e12250a096368616e6e656c494418012001280b32122e4368616e" .
            "6e656c4964656e746966696572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

