<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ResolveChannelNameToIdRequest.proto

namespace GPBMetadata\Channel;

class ResolveChannelNameToIdRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a2b4368616e6e656c2f5265736f6c76654368616e6e656c4e616d65" .
            "546f4964526571756573742e70726f746f222d0a1d5265736f6c76654368" .
            "616e6e656c4e616d65546f496452657175657374120c0a046e616d651801" .
            "20012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

