<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ResponseStatus.proto

namespace GPBMetadata\Channel;

class ResponseStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89010a1c4368616e6e656c2f526573706f6e73655374617475732e7072" .
            "6f746f2a610a0e526573706f6e7365537461747573120a0a064e6f745365" .
            "74100012060a024f6b100112130a0f4368616e6e656c4e6f74466f756e64" .
            "100212140a104c6f616454696d656f75744572726f72100312100a0c556e" .
            "6b6e6f776e4572726f721004620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

