<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/UserKicked.proto

namespace GPBMetadata\Channel;

class UserKicked
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6010a184368616e6e656c2f557365724b69636b65642e70726f746f22" .
            "81010a0a557365724b69636b656412250a096368616e6e656c4944180120" .
            "01280b32122e4368616e6e656c4964656e74696669657212220a06726561" .
            "736f6e18022001280b32122e557365724b69636b65642e526561736f6e1a" .
            "280a06526561736f6e120c0a047479706518012001280512100a08667265" .
            "6574657874180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

