<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/AuthenticateConnection.proto

namespace GPBMetadata\Core;

class AuthenticateConnection
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a540a21636f72652f41757468656e746963617465436f6e6e656374696f" .
            "6e2e70726f746f22270a1641757468656e746963617465436f6e6e656374" .
            "696f6e120d0a05746f6b656e180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

