<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ClientType.proto

namespace GPBMetadata\Core;

class ClientType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5b0a15636f72652f436c69656e74547970652e70726f746f2a3a0a0a43" .
            "6c69656e745479706512070a035765621000120d0a094d6f62696c655765" .
            "621001120b0a07416e64726f6964100212070a03494f531003620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

