<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ConnectionAuthenticationStateUpdated.proto

namespace GPBMetadata\Core;

class ConnectionAuthenticationStateUpdated
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98010a2f636f72652f436f6e6e656374696f6e41757468656e74696361" .
            "74696f6e5374617465557064617465642e70726f746f225d0a24436f6e6e" .
            "656374696f6e41757468656e7469636174696f6e53746174655570646174" .
            "656412150a0d61757468656e74696361746564180120012808120e0a0672" .
            "6561736f6e180220012809120e0a06757365724944180320012805620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

