<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ConnectResponse.proto

namespace GPBMetadata\Core;

class ConnectResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a660a1a636f72652f436f6e6e656374526573706f6e73652e70726f746f" .
            "22400a0f436f6e6e656374526573706f6e736512140a0c636f6e6e656374" .
            "696f6e496418012001280c12170a0f626164436f6e6e656374696f6e4964" .
            "180220012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

