<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ConnectionType.proto

namespace GPBMetadata\Core;

class ConnectionType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a550a19636f72652f436f6e6e656374696f6e547970652e70726f746f2a" .
            "300a0e436f6e6e656374696f6e54797065120a0a064e6f74536574100012" .
            "0a0a064c6567616379100112060a024b331002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

