<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/DisconnectRequest.proto

namespace GPBMetadata\Core;

class DisconnectRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a620a1c636f72652f446973636f6e6e656374526571756573742e70726f" .
            "746f223a0a11446973636f6e6e65637452657175657374120e0a06726561" .
            "736f6e18012001280912150a0d6d6179626546616c6c6261636b18022001" .
            "2808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

