<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/FormattedText.proto

namespace GPBMetadata\Core;

class FormattedText
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9020a18636f72652f466f726d6174746564546578742e70726f746f22" .
            "d4020a0d466f726d61747465645465787412210a04746578741801200128" .
            "0b32132e466f726d6174746564546578742e5465787412210a046c697374" .
            "18022001280b32132e466f726d6174746564546578742e4c69737412250a" .
            "06736d696c657918032001280b32152e466f726d6174746564546578742e" .
            "536d696c657912210a046c696e6b18042001280b32132e466f726d617474" .
            "6564546578742e4c696e6b1a320a0454657874120c0a0474657874180120" .
            "012809120c0a04626f6c64180220012808120e0a066974616c6963180320" .
            "0128081a250a044c697374121d0a056974656d7318012003280b320e2e46" .
            "6f726d6174746564546578741a160a06536d696c6579120c0a046a736f6e" .
            "1801200128091a400a044c696e6b120c0a0468726566180120012809120c" .
            "0a0474657874180220012809120c0a04626f6c64180320012808120e0a06" .
            "6974616c6963180420012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

