<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Gender.proto

namespace GPBMetadata\Core;

class Gender
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a480a11636f72652f47656e6465722e70726f746f2a2b0a0647656e6465" .
            "72120b0a07554e4b4e4f574e100012080a044d414c451001120a0a064645" .
            "4d414c451002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

