<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/MessageWindow.proto

namespace GPBMetadata\Core;

class MessageWindow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a620a18636f72652f4d65737361676557696e646f772e70726f746f223e" .
            "0a0d4d65737361676557696e646f77120d0a057469746c65180120012809" .
            "12100a08686561646c696e65180220012809120c0a047465787418032001" .
            "2809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

