<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/NewProtocol.proto

namespace GPBMetadata\Core;

class NewProtocol
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a3d0a16636f72652f4e657750726f746f636f6c2e70726f746f221b0a0b" .
            "4e657750726f746f636f6c120c0a046461746118012001280c620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

