<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ClientSettings.proto

namespace ClientSettings;

use UnexpectedValueException;

/**
 * Protobuf type <code>ClientSettings.ConversationListFilterType</code>
 */
class ConversationListFilterType
{
    /**
     * Generated from protobuf enum <code>NotSet = 0;</code>
     */
    const NotSet = 0;
    /**
     * Generated from protobuf enum <code>AllMessages = 1;</code>
     */
    const AllMessages = 1;
    /**
     * Generated from protobuf enum <code>UnreadMessagesOnly = 2;</code>
     */
    const UnreadMessagesOnly = 2;

    private static $valueToName = [
        self::NotSet => 'NotSet',
        self::AllMessages => 'AllMessages',
        self::UnreadMessagesOnly => 'UnreadMessagesOnly',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ConversationListFilterType::class, \ClientSettings_ConversationListFilterType::class);

