<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckFlag.proto

namespace CheckFlag;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>CheckFlag.FlagCheckResponse</code>
 */
class FlagCheckResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .CheckFlag.FlagCheckResponse.Result results = 1;</code>
     */
    private $results;
    /**
     * Generated from protobuf field <code>bool authenticationFailed = 2;</code>
     */
    private $authenticationFailed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CheckFlag\FlagCheckResponse\Result[]|\Google\Protobuf\Internal\RepeatedField $results
     *     @type bool $authenticationFailed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CheckFlag::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .CheckFlag.FlagCheckResponse.Result results = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * Generated from protobuf field <code>repeated .CheckFlag.FlagCheckResponse.Result results = 1;</code>
     * @param \CheckFlag\FlagCheckResponse\Result[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CheckFlag\FlagCheckResponse\Result::class);
        $this->results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool authenticationFailed = 2;</code>
     * @return bool
     */
    public function getAuthenticationFailed()
    {
        return $this->authenticationFailed;
    }

    /**
     * Generated from protobuf field <code>bool authenticationFailed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAuthenticationFailed($var)
    {
        GPBUtil::checkBool($var);
        $this->authenticationFailed = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FlagCheckResponse::class, \CheckFlag_FlagCheckResponse::class);

