<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckFlag.proto

namespace CheckFlag;

use UnexpectedValueException;

/**
 * Protobuf type <code>CheckFlag.Flag</code>
 */
class Flag
{
    /**
     * Generated from protobuf enum <code>CAN_USE_K3_CLIENT = 0;</code>
     */
    const CAN_USE_K3_CLIENT = 0;

    private static $valueToName = [
        self::CAN_USE_K3_CLIENT => 'CAN_USE_K3_CLIENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Flag::class, \CheckFlag_Flag::class);

