<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/IgnoreListComplete.proto

namespace GPBMetadata\UserData;

class IgnoreListComplete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7a0a2155736572446174612f49676e6f72654c697374436f6d706c6574" .
            "652e70726f746f224d0a1249676e6f72654c697374436f6d706c65746512" .
            "0f0a0769676e6f726573180120032805120e0a06626c6f636b7318022003" .
            "280512160a0e7072697661746549676e6f72657318032003280562067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

