<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/RequestUserDataByNick.proto

namespace GPBMetadata\UserData;

class RequestUserDataByNick
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserData\UserDataByNickRequest::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a710a2455736572446174612f5265717565737455736572446174614279" .
            "4e69636b2e70726f746f22410a1552657175657374557365724461746142" .
            "794e69636b12280a08726571756573747318012001280b32162e55736572" .
            "4461746142794e69636b52657175657374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

