<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/RequestUserData.proto

namespace GPBMetadata\UserData;

class RequestUserData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserData\UserDataRequest::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5f0a1e55736572446174612f5265717565737455736572446174612e70" .
            "726f746f22350a0f52657175657374557365724461746112220a08726571" .
            "756573747318012003280b32102e55736572446174615265717565737462" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

