<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/RequestIgnoreList.proto

namespace GPBMetadata\UserData;

class RequestIgnoreList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a3f0a2055736572446174612f5265717565737449676e6f72654c697374" .
            "2e70726f746f22130a115265717565737449676e6f72654c697374620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

