<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/UserDataRequest.proto

namespace GPBMetadata\UserData;

class UserDataRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a580a1e55736572446174612f5573657244617461526571756573742e70" .
            "726f746f222e0a0f557365724461746152657175657374120b0a03756964" .
            "180120012805120e0a066669656c6473180220032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

