<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/Userfield.proto

namespace GPBMetadata\UserData;

class Userfield
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a1855736572446174612f557365726669656c642e70726f746f2a" .
            "a3010a09557365726669656c64120c0a084e69636b6e616d65100012070a" .
            "034167651001120a0a0647656e6465721002120a0a06526561644d651003" .
            "120c0a0844697374616e6365100412100a0c4f6e6c696e65537461747573" .
            "1005120b0a074368616e6e656c1006120e0a0a497349676e6f72696e6710" .
            "07120c0a0849734164467265651008120f0a0b4163636f756e7454797065" .
            "1009120b0a07426f74496e666f100a620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

