<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/UserDataByNickRequest.proto

namespace GPBMetadata\UserData;

class UserDataByNickRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a650a2455736572446174612f557365724461746142794e69636b526571" .
            "756573742e70726f746f22350a15557365724461746142794e69636b5265" .
            "7175657374120c0a046e69636b180120012809120e0a066669656c647318" .
            "0220032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

