<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/UserOnlineStatus.proto

namespace GPBMetadata\UserData;

class UserOnlineStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6b0a1f55736572446174612f557365724f6e6c696e655374617475732e" .
            "70726f746f2a400a10557365724f6e6c696e65537461747573120b0a074f" .
            "66666c696e651000120a0a064f6e6c696e65100112130a0f4f6e6c696e65" .
            "496e4368616e6e656c1002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

