<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/CreateDeviceTokenWebRequest.proto

namespace GPBMetadata\Login;

class CreateDeviceTokenWebRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Login\Credentials::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a730a276c6f67696e2f437265617465446576696365546f6b656e576562" .
            "526571756573742e70726f746f22400a1b43726561746544657669636554" .
            "6f6b656e5765625265717565737412210a0b63726564656e7469616c7318" .
            "012001280b320c2e43726564656e7469616c73620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

