<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/CreateTokenWebResponse.proto

namespace GPBMetadata\Login;

class CreateTokenWebResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a650a226c6f67696e2f437265617465546f6b656e576562526573706f6e" .
            "73652e70726f746f22370a16437265617465546f6b656e57656252657370" .
            "6f6e7365120d0a05746f6b656e180120012809120e0a06726573756c7418" .
            "0220012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

