<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/Credentials.proto

namespace GPBMetadata\Login;

class Credentials
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Login\PasswordCredentialsData::initOnce();
        \GPBMetadata\Login\FacebookCredentialsData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc010a176c6f67696e2f43726564656e7469616c732e70726f746f1a23" .
            "6c6f67696e2f46616365626f6f6b43726564656e7469616c73446174612e" .
            "70726f746f2293010a0b43726564656e7469616c7312160a0e6372656465" .
            "6e7469616c5479706518012001280512350a1370617373776f7264437265" .
            "64656e7469616c7318022001280b32182e50617373776f72644372656465" .
            "6e7469616c734461746112350a1366616365626f6f6b43726564656e7469" .
            "616c7318032001280b32182e46616365626f6f6b43726564656e7469616c" .
            "7344617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

