<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/DeviceTokenData.proto

namespace GPBMetadata\Login;

class DeviceTokenData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a380a1b6c6f67696e2f446576696365546f6b656e446174612e70726f74" .
            "6f22110a0f446576696365546f6b656e44617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

