<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/FacebookCredentialsData.proto

namespace GPBMetadata\Login;

class FacebookCredentialsData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a570a236c6f67696e2f46616365626f6f6b43726564656e7469616c7344" .
            "6174612e70726f746f22280a1746616365626f6f6b43726564656e746961" .
            "6c7344617461120d0a05746f6b656e180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

