<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/InitiatePasswordResetWebResult.proto

namespace GPBMetadata\Login;

class InitiatePasswordResetWebResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1020a2a6c6f67696e2f496e69746961746550617373776f7264526573" .
            "6574576562526573756c742e70726f746f2a8a020a1e496e697469617465" .
            "50617373776f72645265736574576562526573756c7412200a1c496e6974" .
            "6961746550617373776f726452657365745f4e6f74536574100012210a1d" .
            "496e69746961746550617373776f726452657365745f5375636365737310" .
            "01122d0a29496e69746961746550617373776f726452657365745f536572" .
            "766963654e6f74417661696c61626c65100212240a20496e697469617465" .
            "50617373776f726452657365745f4e6f5375636855736572100312210a1d" .
            "496e69746961746550617373776f726452657365745f4e6f456d61696c10" .
            "04122b0a27496e69746961746550617373776f726452657365745f496e76" .
            "616c6964557365725374617475731005620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

