<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/SetPasswordCredentialsWebResponse.proto

namespace GPBMetadata\Login;

class SetPasswordCredentialsWebResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6c0a2d6c6f67696e2f53657450617373776f726443726564656e746961" .
            "6c73576562526573706f6e73652e70726f746f22330a2153657450617373" .
            "776f726443726564656e7469616c73576562526573706f6e7365120e0a06" .
            "726573756c74180120012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

