<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/SetPasswordCredentialsWebResult.proto

namespace GPBMetadata\Login;

class SetPasswordCredentialsWebResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6010a2b6c6f67696e2f53657450617373776f726443726564656e7469" .
            "616c73576562526573756c742e70726f746f2abe010a1f53657450617373" .
            "776f726443726564656e7469616c73576562526573756c7412210a1d5365" .
            "7450617373776f726443726564656e7469616c735f4e6f74536574100012" .
            "2b0a2753657450617373776f726443726564656e7469616c735f496e7661" .
            "6c6964506172616d65746572100112270a2353657450617373776f726443" .
            "726564656e7469616c735f496e76616c6964546f6b656e100212220a1e53" .
            "657450617373776f726443726564656e7469616c735f5375636365737310" .
            "03620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

