<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/TokenType.proto

namespace GPBMetadata\Login;

class TokenType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a580a156c6f67696e2f546f6b656e547970652e70726f746f2a370a0954" .
            "6f6b656e54797065120a0a064e6f745365741000120a0a06446576696365" .
            "100112120a0e50617373776f72644368616e67651002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

