<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/TokenPayload.proto

namespace GPBMetadata\Login;

class TokenPayload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Login\DeviceTokenData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a186c6f67696e2f546f6b656e5061796c6f61642e70726f746f2257" .
            "0a0c546f6b656e5061796c6f6164120c0a0474797065180120012805120e" .
            "0a0675736572496418022001280312290a0f646576696365546f6b656e44" .
            "61746118032001280b32102e446576696365546f6b656e44617461620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

