<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/TokenRequestResult.proto

namespace GPBMetadata\Login;

class TokenRequestResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af3010a1e6c6f67696e2f546f6b656e52657175657374526573756c742e" .
            "70726f746f2ac8010a12546f6b656e52657175657374526573756c74121d" .
            "0a19546f6b656e52657175657374526573756c745f4e6f74536574100012" .
            "1e0a1a546f6b656e52657175657374526573756c745f5375636365737310" .
            "0112220a1e546f6b656e52657175657374526573756c745f55736572556e" .
            "6b6e6f776e100212290a25546f6b656e52657175657374526573756c745f" .
            "496e76616c696443726564656e7469616c73100312240a20546f6b656e52" .
            "657175657374526573756c745f496e7465726e616c4572726f7210046206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

