<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/ValidateAuthTokenWebResult.proto

namespace GPBMetadata\Login;

class ValidateAuthTokenWebResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b020a266c6f67696e2f56616c696461746541757468546f6b656e5765" .
            "62526573756c742e70726f746f2ae8010a1a56616c696461746541757468" .
            "546f6b656e576562526573756c74121c0a1856616c696461746541757468" .
            "546f6b656e5f4e6f745365741000121b0a1756616c696461746541757468" .
            "546f6b656e5f56616c69641001121d0a1956616c69646174654175746854" .
            "6f6b656e5f45787069726564100212220a1e56616c696461746541757468" .
            "546f6b656e5f556e6b6e6f776e546f6b656e100312240a2056616c696461" .
            "746541757468546f6b656e5f496e76616c69645265717565737410041226" .
            "0a2256616c696461746541757468546f6b656e5f496e76616c6964536967" .
            "6e61747572651005620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

