<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/ValidateAuthTokenWebResponse.proto

namespace GPBMetadata\Login;

class ValidateAuthTokenWebResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Login\TokenPayload::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7010a286c6f67696e2f56616c696461746541757468546f6b656e5765" .
            "62526573706f6e73652e70726f746f2292010a1c56616c69646174654175" .
            "7468546f6b656e576562526573706f6e7365120e0a06726573756c741801" .
            "2001280512200a09746f6b656e4461746118022001280b320d2e546f6b65" .
            "6e5061796c6f616412100a08757365726e616d6518032001280912170a0f" .
            "6163636f756e7444697361626c656418042001280812150a0d6469736162" .
            "6c65526561736f6e180520012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

