<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UpdateInContactEndTimeRequest.proto

namespace UpdateInContactEndTimeRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>UpdateInContactEndTimeRequest.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>TUTANT = 1;</code>
     */
    const TUTANT = 1;
    /**
     * Generated from protobuf enum <code>FRIEND = 2;</code>
     */
    const FRIEND = 2;
    /**
     * Generated from protobuf enum <code>WATCH_LIST = 3;</code>
     */
    const WATCH_LIST = 3;
    /**
     * Generated from protobuf enum <code>FOTO_MEET = 4;</code>
     */
    const FOTO_MEET = 4;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::TUTANT => 'TUTANT',
        self::FRIEND => 'FRIEND',
        self::WATCH_LIST => 'WATCH_LIST',
        self::FOTO_MEET => 'FOTO_MEET',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \UpdateInContactEndTimeRequest_Status::class);

