<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArchiveConversationStatusResponse.proto

namespace GPBMetadata;

class ArchiveConversationStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a2741726368697665436f6e766572736174696f6e537461747573" .
            "526573706f6e73652e70726f746f2294010a2141726368697665436f6e76" .
            "6572736174696f6e537461747573526573706f6e736512390a0673746174" .
            "757318012001280e32292e41726368697665436f6e766572736174696f6e" .
            "537461747573526573706f6e73652e53746174757312160a0e636f6e7665" .
            "72736174696f6e4964180220012803221c0a0653746174757312060a024f" .
            "4b1000120a0a064641494c45441001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

