<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthenticateConnection.proto

namespace GPBMetadata;

class AuthenticateConnection
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4f0a1c41757468656e746963617465436f6e6e656374696f6e2e70726f" .
            "746f22270a1641757468656e746963617465436f6e6e656374696f6e120d" .
            "0a05746f6b656e180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

