<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CannotJoinChannel.proto

namespace GPBMetadata;

class CannotJoinChannel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7020a1743616e6e6f744a6f696e4368616e6e656c2e70726f746f2283" .
            "020a1143616e6e6f744a6f696e4368616e6e656c12250a096368616e6e65" .
            "6c494418012001280b32122e4368616e6e656c4964656e74696669657212" .
            "130a0b6368616e6e656c6e616d6518022001280912290a06726561736f6e" .
            "18032001280b32192e43616e6e6f744a6f696e4368616e6e656c2e526561" .
            "736f6e1a280a06526561736f6e120c0a047479706518012001280512100a" .
            "086672656574657874180220012809225d0a0454797065120e0a0a504552" .
            "4d495353494f4e1000120a0a0642414e4e4544100112080a0446554c4c10" .
            "0212100a0c524551554952454d454e5453100312120a0e444f45535f4e4f" .
            "545f4558495354100412090a054f544845521005620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

