<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelDataResponse.proto

namespace GPBMetadata;

class ChannelDataResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a194368616e6e656c44617461526573706f6e73652e70726f746f22" .
            "490a134368616e6e656c44617461526573706f6e736512160a0e72657370" .
            "6f6e7365537461747573180120012805121a0a046461746118022001280b" .
            "320c2e4368616e6e656c44617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

