<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelIdentifier.proto

namespace GPBMetadata;

class ChannelIdentifier
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5c0a174368616e6e656c4964656e7469666965722e70726f746f22390a" .
            "114368616e6e656c4964656e746966696572120e0a06726f6f7449641801" .
            "2001280312140a0c7375626368616e6e656c496418022001280362067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

