<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelListRequest.proto

namespace GPBMetadata;

class ChannelListRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a380a184368616e6e656c4c697374526571756573742e70726f746f2214" .
            "0a124368616e6e656c4c69737452657175657374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

