<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelData.proto

namespace GPBMetadata;

class ChannelData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a114368616e6e656c446174612e70726f746f22da010a0b436861" .
            "6e6e656c44617461121e0a02696418012001280b32122e4368616e6e656c" .
            "4964656e746966696572120c0a046e616d65180220012809120e0a066d69" .
            "6e416765180320012805120e0a066d617841676518042001280512130a0b" .
            "6d6178436861747465727318052001280512120a0a63617465676f726965" .
            "73180620032805120f0a0776697369626c6518072001280812110a097573" .
            "6572436f756e7418082001280512170a0f70726576696577496d61676555" .
            "726c18092001280912170a0f6261636b67726f756e64436f6c6f72180a20" .
            "012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

