<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelListResponse.proto

namespace GPBMetadata;

class ChannelListResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a600a194368616e6e656c4c697374526573706f6e73652e70726f746f22" .
            "3b0a134368616e6e656c4c697374526573706f6e736512240a086368616e" .
            "6e656c7318012003280b32122e4368616e6e656c4964656e746966696572" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

