<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelDataRequest.proto

namespace GPBMetadata;

class ChannelDataRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6f0a184368616e6e656c44617461526571756573742e70726f746f224b" .
            "0a124368616e6e656c446174615265717565737412250a096368616e6e65" .
            "6c496418012001280b32122e4368616e6e656c4964656e74696669657212" .
            "0e0a066669656c6473180220032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

