<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelDataId.proto

namespace GPBMetadata;

class ChannelDataId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abf010a134368616e6e656c4461746149642e70726f746f2a9f010a0d43" .
            "68616e6e656c44617461496412060a024964100012080a044e616d651001" .
            "120a0a064d696e4167651002120a0a064d61784167651003120f0a0b4d61" .
            "7843686174746572731004120d0a094170706c65744964731005120b0a07" .
            "56697369626c651006120d0a0955736572436f756e74100712130a0f5072" .
            "6576696577496d61676555726c100812130a0f4261636b67726f756e6443" .
            "6f6c6f721009620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

