<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckFlag.proto

namespace GPBMetadata;

class CheckFlag
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f020a0f436865636b466c61672e70726f746f22f3010a09436865636b" .
            "466c61671a350a1052657175657374466c6167436865636b120b0a036a77" .
            "7418012001280912140a0c666c616773546f436865636b1802200328051a" .
            "8f010a11466c6167436865636b526573706f6e736512340a07726573756c" .
            "747318012003280b32232e436865636b466c61672e466c6167436865636b" .
            "526573706f6e73652e526573756c74121c0a1461757468656e7469636174" .
            "696f6e4661696c65641802200128081a260a06526573756c74120c0a0466" .
            "6c6167180120012805120e0a06706173736564180220012808221d0a0446" .
            "6c616712150a1143414e5f5553455f4b335f434c49454e54100062067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

