<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientType.proto

namespace GPBMetadata;

class ClientType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a560a10436c69656e74547970652e70726f746f2a3a0a0a436c69656e74" .
            "5479706512070a035765621000120d0a094d6f62696c655765621001120b" .
            "0a07416e64726f6964100212070a03494f531003620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

