<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConnectionType.proto

namespace GPBMetadata;

class ConnectionType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a500a14436f6e6e656374696f6e547970652e70726f746f2a300a0e436f" .
            "6e6e656374696f6e54797065120a0a064e6f745365741000120a0a064c65" .
            "67616379100112060a024b331002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

