<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConnectResponse.proto

namespace GPBMetadata;

class ConnectResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a610a15436f6e6e656374526573706f6e73652e70726f746f22400a0f43" .
            "6f6e6e656374526573706f6e736512140a0c636f6e6e656374696f6e4964" .
            "18012001280c12170a0f626164436f6e6e656374696f6e49641802200128" .
            "08620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

