<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactList.proto

namespace GPBMetadata;

class ContactList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a3b0a11436f6e746163744c6973742e70726f746f221e0a0b436f6e7461" .
            "63744c697374120f0a0775736572496473180120032805620670726f746f" .
            "33"
        ), true);

        static::$is_initialized = true;
    }
}

