<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CreateTokenWebResponse.proto

namespace GPBMetadata;

class CreateTokenWebResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5f0a1c437265617465546f6b656e576562526573706f6e73652e70726f" .
            "746f22370a16437265617465546f6b656e576562526573706f6e7365120d" .
            "0a05746f6b656e180120012809120e0a06726573756c7418022001280562" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

