<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CredentialsType.proto

namespace GPBMetadata;

class CredentialsType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a1543726564656e7469616c73547970652e70726f746f2a690a0f" .
            "43726564656e7469616c7354797065121a0a1643726564656e7469616c73" .
            "547970655f4e6f745365741000121c0a1843726564656e7469616c735479" .
            "70655f50617373776f72641001121c0a1843726564656e7469616c735479" .
            "70655f46616365626f6f6b1002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

