<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DisconnectedByLegacyClientConnectEvent.proto

namespace GPBMetadata;

class DisconnectedByLegacyClientConnectEvent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a700a2c446973636f6e6e656374656442794c6567616379436c69656e74" .
            "436f6e6e6563744576656e742e70726f746f22380a26446973636f6e6e65" .
            "6374656442794c6567616379436c69656e74436f6e6e6563744576656e74" .
            "120e0a06757365724964180120012804620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

