<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ErrorInfo.proto

namespace GPBMetadata;

class ErrorInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89010a0f4572726f72496e666f2e70726f746f2a6e0a094572726f7249" .
            "6e666f120d0a096669656c644e616d651000120d0a096572726f72547970" .
            "65100112100a0c6572726f7253756254797065100212070a036d696e1003" .
            "12070a036d61781004120f0a0b70726f626c656d436861721005120e0a0a" .
            "637573746f6d496e666f1006620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

