<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FacebookCredentialsData.proto

namespace GPBMetadata;

class FacebookCredentialsData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a510a1d46616365626f6f6b43726564656e7469616c73446174612e7072" .
            "6f746f22280a1746616365626f6f6b43726564656e7469616c7344617461" .
            "120d0a05746f6b656e180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

