<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardMessage.proto

namespace GPBMetadata;

class ForwardMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5f0a14466f72776172644d6573736167652e70726f746f223f0a0e466f" .
            "72776172644d65737361676512110a097265636569766572731801200328" .
            "05121a0a12666f727761726465644d657373616765496418022001280362" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

