<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardMessageStatusResponse.proto

namespace GPBMetadata;

class ForwardMessageStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acf010a22466f72776172644d657373616765537461747573526573706f" .
            "6e73652e70726f746f22a0010a1c466f72776172644d6573736167655374" .
            "61747573526573706f6e736512340a0673746174757318012001280e3224" .
            "2e466f72776172644d657373616765537461747573526573706f6e73652e" .
            "53746174757312140a0c736f757263655573657249641802200128051216" .
            "0a0e726563697069656e74436f756e74180320012805221c0a0653746174" .
            "757312060a024f4b1000120a0a064641494c45441001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

