<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gender.proto

namespace GPBMetadata;

class Gender
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a430a0c47656e6465722e70726f746f2a2b0a0647656e646572120b0a07" .
            "554e4b4e4f574e100012080a044d414c451001120a0a0646454d414c4510" .
            "02620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

