<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetClientSettingsRequest.proto

namespace GPBMetadata;

class GetClientSettingsRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a440a1e476574436c69656e7453657474696e6773526571756573742e70" .
            "726f746f221a0a18476574436c69656e7453657474696e67735265717565" .
            "7374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

