<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IgnoreListComplete.proto

namespace GPBMetadata;

class IgnoreListComplete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a710a1849676e6f72654c697374436f6d706c6574652e70726f746f224d" .
            "0a1249676e6f72654c697374436f6d706c657465120f0a0769676e6f7265" .
            "73180120032805120e0a06626c6f636b7318022003280512160a0e707269" .
            "7661746549676e6f726573180320032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

