<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IgnoreStateAction.proto

namespace GPBMetadata;

class IgnoreStateAction
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b010a1749676e6f72655374617465416374696f6e2e70726f746f2a78" .
            "0a1149676e6f72655374617465416374696f6e120a0a0649474e4f524510" .
            "00120c0a08554e49474e4f5245100112090a05424c4f434b1002120b0a07" .
            "554e424c4f434b100312160a124144445f505249564154455f49474e4f52" .
            "45100412190a1552454d4f56455f505249564154455f49474e4f52451005" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

