<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InitialChannelJoin.proto

namespace GPBMetadata;

class InitialChannelJoin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a380a18496e697469616c4368616e6e656c4a6f696e2e70726f746f2214" .
            "0a12496e697469616c4368616e6e656c4a6f696e620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

