<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InitiatePasswordResetWebResponse.proto

namespace GPBMetadata;

class InitiatePasswordResetWebResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a26496e69746961746550617373776f726452657365745765625265" .
            "73706f6e73652e70726f746f22320a20496e69746961746550617373776f" .
            "72645265736574576562526573706f6e7365120e0a06726573756c741801" .
            "20012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

