<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InitiatePasswordResetWebResult.proto

namespace GPBMetadata;

class InitiatePasswordResetWebResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb020a24496e69746961746550617373776f7264526573657457656252" .
            "6573756c742e70726f746f2a8a020a1e496e69746961746550617373776f" .
            "72645265736574576562526573756c7412200a1c496e6974696174655061" .
            "7373776f726452657365745f4e6f74536574100012210a1d496e69746961" .
            "746550617373776f726452657365745f537563636573731001122d0a2949" .
            "6e69746961746550617373776f726452657365745f536572766963654e6f" .
            "74417661696c61626c65100212240a20496e69746961746550617373776f" .
            "726452657365745f4e6f5375636855736572100312210a1d496e69746961" .
            "746550617373776f726452657365745f4e6f456d61696c1004122b0a2749" .
            "6e69746961746550617373776f726452657365745f496e76616c69645573" .
            "65725374617475731005620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

