<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JoinChannel.proto

namespace GPBMetadata;

class JoinChannel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a114a6f696e4368616e6e656c2e70726f746f224d0a0b4a6f696e43" .
            "68616e6e656c12250a096368616e6e656c494418012001280b32122e4368" .
            "616e6e656c4964656e74696669657212170a0f616c6c6f77537562436861" .
            "6e6e656c180220012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

