<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JoinChannelByName.proto

namespace GPBMetadata;

class JoinChannelByName
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a174a6f696e4368616e6e656c42794e616d652e70726f746f22410a" .
            "114a6f696e4368616e6e656c42794e616d6512130a0b6368616e6e656c4e" .
            "616d6518012001280912170a0f616c6c6f775375624368616e6e656c1802" .
            "20012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

