<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageWindow.proto

namespace GPBMetadata;

class MessageWindow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5d0a134d65737361676557696e646f772e70726f746f223e0a0d4d6573" .
            "7361676557696e646f77120d0a057469746c6518012001280912100a0868" .
            "6561646c696e65180220012809120c0a0474657874180320012809620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

