<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageInChannel.proto

namespace GPBMetadata;

class MessageInChannel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6c0a164d657373616765496e4368616e6e656c2e70726f746f224a0a10" .
            "4d657373616765496e4368616e6e656c12250a096368616e6e656c494418" .
            "012001280b32122e4368616e6e656c4964656e746966696572120f0a076d" .
            "657373616765180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

