<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageID.proto

namespace GPBMetadata;

class MessageID
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a630a0f4d65737361676549442e70726f746f22480a094d657373616765" .
            "494412250a096368616e6e656c494418012001280b32122e4368616e6e65" .
            "6c4964656e74696669657212140a0c6d657373616765436f756e74180220" .
            "012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

