<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageSendError.proto

namespace GPBMetadata;

class MessageSendError
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a164d65737361676553656e644572726f722e70726f746f227a0a" .
            "104d65737361676553656e644572726f72122b0a06726561736f6e180120" .
            "01280e321b2e4d65737361676553656e644572726f722e4572726f725479" .
            "7065120c0a0474657874180220012809222b0a094572726f725479706512" .
            "130a0f4e69636b6e616d65496e76616c6964100012090a054f7468657210" .
            "01620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

