<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NicklistChange.proto

namespace GPBMetadata;

class NicklistChange
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserNicklistData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a610a144e69636b6c6973744368616e67652e70726f746f22410a0e4e69" .
            "636b6c6973744368616e6765121f0a047573657218012001280b32112e55" .
            "7365724e69636b6c69737444617461120e0a06616374696f6e1802200128" .
            "05620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

