<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NicklistUpdate.proto

namespace GPBMetadata;

class NicklistUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        \GPBMetadata\NicklistChange::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5010a144e69636b6c6973745570646174652e70726f746f1a144e6963" .
            "6b6c6973744368616e67652e70726f746f226f0a0e4e69636b6c69737455" .
            "706461746512250a096368616e6e656c494418012001280b32122e436861" .
            "6e6e656c4964656e74696669657212150a0d76657273696f6e4e756d6265" .
            "72180220012803121f0a066368616e676518032003280b320f2e4e69636b" .
            "6c6973744368616e6765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

