<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NicklistBootstrap.proto

namespace GPBMetadata;

class NicklistBootstrap
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        \GPBMetadata\UserNicklistData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4010a174e69636b6c697374426f6f7473747261702e70726f746f1a16" .
            "557365724e69636b6c697374446174612e70726f746f2288010a114e6963" .
            "6b6c697374426f6f74737472617012250a096368616e6e656c4944180120" .
            "01280b32122e4368616e6e656c4964656e74696669657212150a0d766572" .
            "73696f6e4e756d62657218022001280312200a056e69636b731803200328" .
            "0b32112e557365724e69636b6c6973744461746112130a0b6368616e6e65" .
            "6c4e616d65180420012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

