<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OnlineUsersRequest.proto

namespace GPBMetadata;

class OnlineUsersRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5f0a184f6e6c696e655573657273526571756573742e70726f746f223b" .
            "0a124f6e6c696e6555736572735265717565737412250a096368616e6e65" .
            "6c496418012001280b32122e4368616e6e656c4964656e74696669657262" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

