<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PasswordCredentialsData.proto

namespace GPBMetadata;

class PasswordCredentialsData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a660a1d50617373776f726443726564656e7469616c73446174612e7072" .
            "6f746f223d0a1750617373776f726443726564656e7469616c7344617461" .
            "12100a08757365726e616d6518012001280912100a0870617373776f7264" .
            "180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

