<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QuoteMessage.proto

namespace GPBMetadata;

class QuoteMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d010a1251756f74654d6573736167652e70726f746f227f0a0c51756f" .
            "74654d65737361676512110a09726563656976657273180120032805120c" .
            "0a0474657874180220012809120f0a0771756f7465496418032001280312" .
            "210a19697351756f74654f66466f727761726465644d6573736167651804" .
            "20012808121a0a12666f727761726465644d657373616765496418052001" .
            "2803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

