<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReadAllConversations.proto

namespace GPBMetadata;

class ReadAllConversations
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a540a1a52656164416c6c436f6e766572736174696f6e732e70726f746f" .
            "222e0a1452656164416c6c436f6e766572736174696f6e7312160a0e636f" .
            "6e766572736174696f6e4964180120032803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

