<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReadMessages.proto

namespace GPBMetadata;

class ReadMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a3f0a12526561644d657373616765732e70726f746f22210a0c52656164" .
            "4d6573736167657312110a096d6573736167654964180120032803620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

