<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestContactList.proto

namespace GPBMetadata;

class RequestContactList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a380a1852657175657374436f6e746163744c6973742e70726f746f2214" .
            "0a1252657175657374436f6e746163744c697374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

