<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestConversations.proto

namespace GPBMetadata;

class RequestConversations
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a1a52657175657374436f6e766572736174696f6e732e70726f746f" .
            "22440a1452657175657374436f6e766572736174696f6e7312160a0e7369" .
            "6e636554696d657374616d7018012001280312140a0c6d6573736167654c" .
            "696d6974180220012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

