<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestStarredMessages.proto

namespace GPBMetadata;

class RequestStarredMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a400a1c52657175657374537461727265644d657373616765732e70726f" .
            "746f22180a1652657175657374537461727265644d657373616765736206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

