<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestIgnoreList.proto

namespace GPBMetadata;

class RequestIgnoreList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a360a175265717565737449676e6f72654c6973742e70726f746f22130a" .
            "115265717565737449676e6f72654c697374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

