<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestType.proto

namespace GPBMetadata;

class RequestType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95010a1152657175657374547970652e70726f746f2a780a0b52657175" .
            "6573745479706512070a03414c4c100012080a044e49434b100112070a03" .
            "4147451002120a0a0647454e444552100312090a05454d41494c1004120c" .
            "0a0850415353574f5244100512070a034341501006120f0a0b46554c4c5f" .
            "5245475f56311007120e0a0a434841545345525645521008620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

