<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestNicklistIntern.proto

namespace GPBMetadata;

class RequestNicklistIntern
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a650a1b526571756573744e69636b6c697374496e7465726e2e70726f74" .
            "6f223e0a15526571756573744e69636b6c697374496e7465726e12250a09" .
            "6368616e6e656c494418012001280b32122e4368616e6e656c4964656e74" .
            "6966696572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

