<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestMessagesForConversation.proto

namespace GPBMetadata;

class RequestMessagesForConversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93010a24526571756573744d65737361676573466f72436f6e76657273" .
            "6174696f6e2e70726f746f22630a1e526571756573744d65737361676573" .
            "466f72436f6e766572736174696f6e12130a0b6f74686572557365724964" .
            "18012001280512160a0e73696e636554696d657374616d70180220012803" .
            "12140a0c6d6573736167654c696d6974180320012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

