<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestNicklistForUser.proto

namespace GPBMetadata;

class RequestNicklistForUser
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a770a1c526571756573744e69636b6c697374466f72557365722e70726f" .
            "746f224f0a16526571756573744e69636b6c697374466f72557365721225" .
            "0a096368616e6e656c494418012001280b32122e4368616e6e656c496465" .
            "6e746966696572120e0a06757365724944180220012805620670726f746f" .
            "33"
        ), true);

        static::$is_initialized = true;
    }
}

