<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResolveChannelNameToIdResponse.proto

namespace GPBMetadata;

class ResolveChannelNameToIdResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f010a245265736f6c76654368616e6e656c4e616d65546f4964526573" .
            "706f6e73652e70726f746f225f0a1e5265736f6c76654368616e6e656c4e" .
            "616d65546f4964526573706f6e736512250a096368616e6e656c49641801" .
            "2001280b32122e4368616e6e656c4964656e74696669657212160a0e7265" .
            "73706f6e7365537461747573180220012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

