<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResolveChannelNameToIdRequest.proto

namespace GPBMetadata;

class ResolveChannelNameToIdRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5c0a235265736f6c76654368616e6e656c4e616d65546f496452657175" .
            "6573742e70726f746f222d0a1d5265736f6c76654368616e6e656c4e616d" .
            "65546f496452657175657374120c0a046e616d6518012001280962067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

