<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResponseStatus.proto

namespace GPBMetadata;

class ResponseStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81010a14526573706f6e73655374617475732e70726f746f2a610a0e52" .
            "6573706f6e7365537461747573120a0a064e6f74536574100012060a024f" .
            "6b100112130a0f4368616e6e656c4e6f74466f756e64100212140a104c6f" .
            "616454696d656f75744572726f72100312100a0c556e6b6e6f776e457272" .
            "6f721004620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

