<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendTyping.proto

namespace GPBMetadata;

class SendTyping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a530a1053656e64547970696e672e70726f746f22370a0a53656e645479" .
            "70696e6712110a0972656365697665727318012003280512160a0e636f6e" .
            "766572736174696f6e4964180220012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

