<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendMessage.proto

namespace GPBMetadata;

class SendMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4b0a1153656e644d6573736167652e70726f746f222e0a0b53656e644d" .
            "65737361676512110a09726563656976657273180120032805120c0a0474" .
            "657874180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

