<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetClientSettingsResponse.proto

namespace GPBMetadata;

class SetClientSettingsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2010a1f536574436c69656e7453657474696e6773526573706f6e7365" .
            "2e70726f746f22770a19536574436c69656e7453657474696e6773526573" .
            "706f6e736512310a06726573756c7418012001280e32212e536574436c69" .
            "656e7453657474696e6773526573706f6e73652e526573756c7422270a06" .
            "526573756c74120a0a064e6f74536574100012060a024f6b100112090a05" .
            "4572726f721002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

