<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetPasswordCredentialsWebRequest.proto

namespace GPBMetadata;

class SetPasswordCredentialsWebRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aac010a2653657450617373776f726443726564656e7469616c73576562" .
            "526571756573742e70726f746f227a0a2053657450617373776f72644372" .
            "6564656e7469616c735765625265717565737412130a0b64657072656361" .
            "7465643118012001280512130a0b64657072656361746564321802200128" .
            "0512110a0961757468546f6b656e18032001280912190a11706c61696e74" .
            "65787450617373776f7264180420012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

