<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetPasswordCredentialsWebResponse.proto

namespace GPBMetadata;

class SetPasswordCredentialsWebResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a660a2753657450617373776f726443726564656e7469616c7357656252" .
            "6573706f6e73652e70726f746f22330a2153657450617373776f72644372" .
            "6564656e7469616c73576562526573706f6e7365120e0a06726573756c74" .
            "180120012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

