<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetPasswordCredentialsWebResult.proto

namespace GPBMetadata;

class SetPasswordCredentialsWebResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af0010a2553657450617373776f726443726564656e7469616c73576562" .
            "526573756c742e70726f746f2abe010a1f53657450617373776f72644372" .
            "6564656e7469616c73576562526573756c7412210a1d5365745061737377" .
            "6f726443726564656e7469616c735f4e6f745365741000122b0a27536574" .
            "50617373776f726443726564656e7469616c735f496e76616c6964506172" .
            "616d65746572100112270a2353657450617373776f726443726564656e74" .
            "69616c735f496e76616c6964546f6b656e100212220a1e53657450617373" .
            "776f726443726564656e7469616c735f537563636573731003620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

