<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetSnapsAllowedStatusResponse.proto

namespace GPBMetadata;

class SetSnapsAllowedStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a23536574536e617073416c6c6f77656453746174757352657370" .
            "6f6e73652e70726f746f2295010a1d536574536e617073416c6c6f776564" .
            "537461747573526573706f6e736512350a0673746174757318012001280e" .
            "32252e536574536e617073416c6c6f776564537461747573526573706f6e" .
            "73652e537461747573120f0a07616c6c6f776564180220012808120e0a06" .
            "757365724964180320012805221c0a0653746174757312060a024f4b1000" .
            "120a0a064641494c45441001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

