<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetTyping.proto

namespace GPBMetadata;

class SetTyping
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a0f536574547970696e672e70726f746f22490a0953657454797069" .
            "6e67120e0a0675736572496418012001280512140a0c7061727469636970" .
            "616e747318022003280512160a0e636f6e766572736174696f6e49641803" .
            "20012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

