<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlashCommand.proto

namespace GPBMetadata;

class SlashCommand
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a12536c617368436f6d6d616e642e70726f746f22460a0c536c6173" .
            "68436f6d6d616e6412250a096368616e6e656c494418012001280b32122e" .
            "4368616e6e656c4964656e746966696572120f0a076d6573736167651802" .
            "20012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

