<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StarMessages.proto

namespace GPBMetadata;

class StarMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a400a12537461724d657373616765732e70726f746f22220a0c53746172" .
            "4d6573736167657312120a0a6d6573736167654964731801200328036206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

