<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Success.proto

namespace GPBMetadata;

class Success
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a0d537563636573732e70726f746f22550a0753756363657373120c" .
            "0a046e69636b18012001280912100a08636865636b73756d180220012809" .
            "12100a086e6578747374657018032001280512180a1073686f77496e7465" .
            "727374697469616c180420012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

