<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TokenType.proto

namespace GPBMetadata;

class TokenType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a520a0f546f6b656e547970652e70726f746f2a370a09546f6b656e5479" .
            "7065120a0a064e6f745365741000120a0a06446576696365100112120a0e" .
            "50617373776f72644368616e67651002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

