<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TokenRequestResult.proto

namespace GPBMetadata;

class TokenRequestResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed010a18546f6b656e52657175657374526573756c742e70726f746f2a" .
            "c8010a12546f6b656e52657175657374526573756c74121d0a19546f6b65" .
            "6e52657175657374526573756c745f4e6f745365741000121e0a1a546f6b" .
            "656e52657175657374526573756c745f53756363657373100112220a1e54" .
            "6f6b656e52657175657374526573756c745f55736572556e6b6e6f776e10" .
            "0212290a25546f6b656e52657175657374526573756c745f496e76616c69" .
            "6443726564656e7469616c73100312240a20546f6b656e52657175657374" .
            "526573756c745f496e7465726e616c4572726f721004620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

