<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnArchiveConversation.proto

namespace GPBMetadata;

class UnArchiveConversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a510a1b556e41726368697665436f6e766572736174696f6e2e70726f74" .
            "6f222a0a15556e41726368697665436f6e766572736174696f6e12110a09" .
            "6d6573736167654964180120012803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

