<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnreadConversation.proto

namespace GPBMetadata;

class UnreadConversation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a500a18556e72656164436f6e766572736174696f6e2e70726f746f222c" .
            "0a12556e72656164436f6e766572736174696f6e12160a0e636f6e766572" .
            "736174696f6e4964180120032803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

