<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnstarMessages.proto

namespace GPBMetadata;

class UnstarMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a440a14556e737461724d657373616765732e70726f746f22240a0e556e" .
            "737461724d6573736167657312120a0a6d65737361676549647318012003" .
            "2803620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

