<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UpdateInContactEndTimeResponse.proto

namespace GPBMetadata;

class UpdateInContactEndTimeResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a24557064617465496e436f6e74616374456e6454696d65526573" .
            "706f6e73652e70726f746f227b0a1e557064617465496e436f6e74616374" .
            "456e6454696d65526573706f6e736512360a067374617475731801200128" .
            "0e32262e557064617465496e436f6e74616374456e6454696d6552657370" .
            "6f6e73652e53746174757322210a06537461747573120b0a075375636365" .
            "73731000120a0a064661696c65641001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

