<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UpdateInContactEndTimeRequest.proto

namespace GPBMetadata;

class UpdateInContactEndTimeRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8020a23557064617465496e436f6e74616374456e6454696d65526571" .
            "756573742e70726f746f22f8010a1d557064617465496e436f6e74616374" .
            "456e6454696d655265717565737412100a0873656e646572496418012001" .
            "280512120a0a7265636569766572496418022001280512140a0c656e6454" .
            "696d657374616d70180320012803123b0a0c757064617465537461747573" .
            "18042001280e32252e557064617465496e436f6e74616374456e6454696d" .
            "65526571756573742e53746174757312130a0b73746174757356616c7565" .
            "18052001280822490a0653746174757312080a044e4f4e451000120a0a06" .
            "545554414e541001120a0a06465249454e441002120e0a0a57415443485f" .
            "4c4953541003120d0a09464f544f5f4d4545541004620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

