<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserKicked.proto

namespace GPBMetadata;

class UserKicked
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ChannelIdentifier::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a10557365724b69636b65642e70726f746f2281010a0a55736572" .
            "4b69636b656412250a096368616e6e656c494418012001280b32122e4368" .
            "616e6e656c4964656e74696669657212220a06726561736f6e1802200128" .
            "0b32122e557365724b69636b65642e526561736f6e1a280a06526561736f" .
            "6e120c0a047479706518012001280512100a086672656574657874180220" .
            "012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

