<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Userfield.proto

namespace GPBMetadata;

class Userfield
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abf010a0f557365726669656c642e70726f746f2aa3010a095573657266" .
            "69656c64120c0a084e69636b6e616d65100012070a034167651001120a0a" .
            "0647656e6465721002120a0a06526561644d651003120c0a084469737461" .
            "6e6365100412100a0c4f6e6c696e655374617475731005120b0a07436861" .
            "6e6e656c1006120e0a0a497349676e6f72696e671007120c0a0849734164" .
            "467265651008120f0a0b4163636f756e74547970651009120b0a07426f74" .
            "496e666f100a620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

