<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserDataByNickRequest.proto

namespace GPBMetadata;

class UserDataByNickRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5c0a1b557365724461746142794e69636b526571756573742e70726f74" .
            "6f22350a15557365724461746142794e69636b52657175657374120c0a04" .
            "6e69636b180120012809120e0a066669656c647318022003280562067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

