<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserDataRequest.proto

namespace GPBMetadata;

class UserDataRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4f0a155573657244617461526571756573742e70726f746f222e0a0f55" .
            "7365724461746152657175657374120b0a03756964180120012805120e0a" .
            "066669656c6473180220032805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

