<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserNicklistData.proto

namespace GPBMetadata;

class UserNicklistData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a16557365724e69636b6c697374446174612e70726f746f22680a" .
            "10557365724e69636b6c69737444617461120e0a06757365724944180120" .
            "01280512100a086e69636b6e616d6518022001280912150a0d6a6f696e54" .
            "696d657374616d70180320012803120b0a03616765180420012805120e0a" .
            "0667656e646572180520012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

