<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ValidateAuthTokenWebResult.proto

namespace GPBMetadata;

class ValidateAuthTokenWebResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95020a2056616c696461746541757468546f6b656e576562526573756c" .
            "742e70726f746f2ae8010a1a56616c696461746541757468546f6b656e57" .
            "6562526573756c74121c0a1856616c696461746541757468546f6b656e5f" .
            "4e6f745365741000121b0a1756616c696461746541757468546f6b656e5f" .
            "56616c69641001121d0a1956616c696461746541757468546f6b656e5f45" .
            "787069726564100212220a1e56616c696461746541757468546f6b656e5f" .
            "556e6b6e6f776e546f6b656e100312240a2056616c696461746541757468" .
            "546f6b656e5f496e76616c696452657175657374100412260a2256616c69" .
            "6461746541757468546f6b656e5f496e76616c69645369676e6174757265" .
            "1005620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

