<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ArchiveConversationStatusResponse.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ArchiveConversationStatusResponse</code>
 */
class ArchiveConversationStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ArchiveConversationStatusResponse.Status status = 1;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>int64 conversationId = 2;</code>
     */
    private $conversationId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type int|string $conversationId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\ArchiveConversationStatusResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ArchiveConversationStatusResponse.Status status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.ArchiveConversationStatusResponse.Status status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \ArchiveConversationStatusResponse_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 2;</code>
     * @return int|string
     */
    public function getConversationId()
    {
        return $this->conversationId;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConversationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->conversationId = $var;

        return $this;
    }

}

