<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ArchiveConversationStatusResponse.proto

if (false) {
    /**
     * This class is deprecated. Use ArchiveConversationStatusResponse\Status instead.
     * @deprecated
     */
    class ArchiveConversationStatusResponse_Status {}
}
class_exists(ArchiveConversationStatusResponse\Status::class);
@trigger_error('ArchiveConversationStatusResponse_Status is deprecated and will be removed in the next major release. Use ArchiveConversationStatusResponse\Status instead', E_USER_DEPRECATED);

