<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/CannotJoinChannel.proto

if (false) {
    /**
     * This class is deprecated. Use CannotJoinChannel\Type instead.
     * @deprecated
     */
    class CannotJoinChannel_Type {}
}
class_exists(CannotJoinChannel\Type::class);
@trigger_error('CannotJoinChannel_Type is deprecated and will be removed in the next major release. Use CannotJoinChannel\Type instead', E_USER_DEPRECATED);

