<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/CannotJoinChannel.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>CannotJoinChannel</code>
 */
class CannotJoinChannel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     */
    private $channelID = null;
    /**
     * Generated from protobuf field <code>string channelname = 2;</code>
     */
    private $channelname = '';
    /**
     * Generated from protobuf field <code>.CannotJoinChannel.Reason reason = 3;</code>
     */
    private $reason = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $channelID
     *     @type string $channelname
     *     @type \CannotJoinChannel\Reason $reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\CannotJoinChannel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getChannelID()
    {
        return $this->channelID;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setChannelID($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->channelID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channelname = 2;</code>
     * @return string
     */
    public function getChannelname()
    {
        return $this->channelname;
    }

    /**
     * Generated from protobuf field <code>string channelname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannelname($var)
    {
        GPBUtil::checkString($var, True);
        $this->channelname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CannotJoinChannel.Reason reason = 3;</code>
     * @return \CannotJoinChannel\Reason
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>.CannotJoinChannel.Reason reason = 3;</code>
     * @param \CannotJoinChannel\Reason $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkMessage($var, \CannotJoinChannel_Reason::class);
        $this->reason = $var;

        return $this;
    }

}

