<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelIdentifier.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ChannelIdentifier</code>
 */
class ChannelIdentifier extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 rootId = 1;</code>
     */
    private $rootId = 0;
    /**
     * Generated from protobuf field <code>int64 subchannelId = 2;</code>
     */
    private $subchannelId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $rootId
     *     @type int|string $subchannelId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\ChannelIdentifier::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 rootId = 1;</code>
     * @return int|string
     */
    public function getRootId()
    {
        return $this->rootId;
    }

    /**
     * Generated from protobuf field <code>int64 rootId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRootId($var)
    {
        GPBUtil::checkInt64($var);
        $this->rootId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 subchannelId = 2;</code>
     * @return int|string
     */
    public function getSubchannelId()
    {
        return $this->subchannelId;
    }

    /**
     * Generated from protobuf field <code>int64 subchannelId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSubchannelId($var)
    {
        GPBUtil::checkInt64($var);
        $this->subchannelId = $var;

        return $this;
    }

}

