<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelDataId.proto

/**
 * Protobuf type <code>ChannelDataId</code>
 */
class ChannelDataId
{
    /**
     * Generated from protobuf enum <code>Id = 0;</code>
     */
    const Id = 0;
    /**
     * Generated from protobuf enum <code>Name = 1;</code>
     */
    const Name = 1;
    /**
     * Generated from protobuf enum <code>MinAge = 2;</code>
     */
    const MinAge = 2;
    /**
     * Generated from protobuf enum <code>MaxAge = 3;</code>
     */
    const MaxAge = 3;
    /**
     * Generated from protobuf enum <code>MaxChatters = 4;</code>
     */
    const MaxChatters = 4;
    /**
     * Generated from protobuf enum <code>AppletIds = 5;</code>
     */
    const AppletIds = 5;
    /**
     * Generated from protobuf enum <code>Visible = 6;</code>
     */
    const Visible = 6;
    /**
     * Generated from protobuf enum <code>UserCount = 7;</code>
     */
    const UserCount = 7;
    /**
     * Generated from protobuf enum <code>PreviewImageUrl = 8;</code>
     */
    const PreviewImageUrl = 8;
    /**
     * Generated from protobuf enum <code>BackgroundColor = 9;</code>
     */
    const BackgroundColor = 9;

    private static $valueToName = [
        self::Id => 'Id',
        self::Name => 'Name',
        self::MinAge => 'MinAge',
        self::MaxAge => 'MaxAge',
        self::MaxChatters => 'MaxChatters',
        self::AppletIds => 'AppletIds',
        self::Visible => 'Visible',
        self::UserCount => 'UserCount',
        self::PreviewImageUrl => 'PreviewImageUrl',
        self::BackgroundColor => 'BackgroundColor',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

