<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ChannelData</code>
 */
class ChannelData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier id = 1;</code>
     */
    private $id = null;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>int32 minAge = 3;</code>
     */
    private $minAge = 0;
    /**
     * Generated from protobuf field <code>int32 maxAge = 4;</code>
     */
    private $maxAge = 0;
    /**
     * Generated from protobuf field <code>int32 maxChatters = 5;</code>
     */
    private $maxChatters = 0;
    /**
     * Generated from protobuf field <code>repeated int32 categories = 6;</code>
     */
    private $categories;
    /**
     * Generated from protobuf field <code>bool visible = 7;</code>
     */
    private $visible = false;
    /**
     * Generated from protobuf field <code>int32 userCount = 8;</code>
     */
    private $userCount = 0;
    /**
     * Generated from protobuf field <code>string previewImageUrl = 9;</code>
     */
    private $previewImageUrl = '';
    /**
     * Generated from protobuf field <code>int32 backgroundColor = 10;</code>
     */
    private $backgroundColor = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $id
     *     @type string $name
     *     @type int $minAge
     *     @type int $maxAge
     *     @type int $maxChatters
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $categories
     *     @type bool $visible
     *     @type int $userCount
     *     @type string $previewImageUrl
     *     @type int $backgroundColor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\ChannelData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier id = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier id = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 minAge = 3;</code>
     * @return int
     */
    public function getMinAge()
    {
        return $this->minAge;
    }

    /**
     * Generated from protobuf field <code>int32 minAge = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMinAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->minAge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maxAge = 4;</code>
     * @return int
     */
    public function getMaxAge()
    {
        return $this->maxAge;
    }

    /**
     * Generated from protobuf field <code>int32 maxAge = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxAge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maxChatters = 5;</code>
     * @return int
     */
    public function getMaxChatters()
    {
        return $this->maxChatters;
    }

    /**
     * Generated from protobuf field <code>int32 maxChatters = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxChatters($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxChatters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 categories = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Generated from protobuf field <code>repeated int32 categories = 6;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->categories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool visible = 7;</code>
     * @return bool
     */
    public function getVisible()
    {
        return $this->visible;
    }

    /**
     * Generated from protobuf field <code>bool visible = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setVisible($var)
    {
        GPBUtil::checkBool($var);
        $this->visible = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 userCount = 8;</code>
     * @return int
     */
    public function getUserCount()
    {
        return $this->userCount;
    }

    /**
     * Generated from protobuf field <code>int32 userCount = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setUserCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->userCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string previewImageUrl = 9;</code>
     * @return string
     */
    public function getPreviewImageUrl()
    {
        return $this->previewImageUrl;
    }

    /**
     * Generated from protobuf field <code>string previewImageUrl = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviewImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->previewImageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 backgroundColor = 10;</code>
     * @return int
     */
    public function getBackgroundColor()
    {
        return $this->backgroundColor;
    }

    /**
     * Generated from protobuf field <code>int32 backgroundColor = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setBackgroundColor($var)
    {
        GPBUtil::checkInt32($var);
        $this->backgroundColor = $var;

        return $this;
    }

}

