<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ChangeIgnoreStateStatusResponse.proto

if (false) {
    /**
     * This class is deprecated. Use ChangeIgnoreStateStatusResponse\Status instead.
     * @deprecated
     */
    class ChangeIgnoreStateStatusResponse_Status {}
}
class_exists(ChangeIgnoreStateStatusResponse\Status::class);
@trigger_error('ChangeIgnoreStateStatusResponse_Status is deprecated and will be removed in the next major release. Use ChangeIgnoreStateStatusResponse\Status instead', E_USER_DEPRECATED);

