<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelDataResponse.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ChannelDataResponse</code>
 */
class ChannelDataResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 responseStatus = 1;</code>
     */
    private $responseStatus = 0;
    /**
     * Generated from protobuf field <code>.ChannelData data = 2;</code>
     */
    private $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $responseStatus
     *     @type \ChannelData $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\ChannelDataResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 responseStatus = 1;</code>
     * @return int
     */
    public function getResponseStatus()
    {
        return $this->responseStatus;
    }

    /**
     * Generated from protobuf field <code>int32 responseStatus = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->responseStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ChannelData data = 2;</code>
     * @return \ChannelData
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.ChannelData data = 2;</code>
     * @param \ChannelData $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \ChannelData::class);
        $this->data = $var;

        return $this;
    }

}

