<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ChangeIgnoreState.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ChangeIgnoreState</code>
 */
class ChangeIgnoreState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     */
    private $userId = 0;
    /**
     * Generated from protobuf field <code>.IgnoreStateAction action = 2;</code>
     */
    private $action = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $userId
     *     @type int $action
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\ChangeIgnoreState::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.IgnoreStateAction action = 2;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>.IgnoreStateAction action = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \IgnoreStateAction::class);
        $this->action = $var;

        return $this;
    }

}

