<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ChangeIgnoreStateStatusResponse.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ChangeIgnoreStateStatusResponse</code>
 */
class ChangeIgnoreStateStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChangeIgnoreStateStatusResponse.Status status = 1;</code>
     */
    private $status = 0;
    /**
     * Enum(5)
     *
     * Generated from protobuf field <code>int32 action = 2;</code>
     */
    private $action = 0;
    /**
     * Generated from protobuf field <code>int32 userId = 3;</code>
     */
    private $userId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type int $action
     *           Enum(5)
     *     @type int $userId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\ChangeIgnoreStateStatusResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChangeIgnoreStateStatusResponse.Status status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.ChangeIgnoreStateStatusResponse.Status status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \ChangeIgnoreStateStatusResponse_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Enum(5)
     *
     * Generated from protobuf field <code>int32 action = 2;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Enum(5)
     *
     * Generated from protobuf field <code>int32 action = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkInt32($var);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 userId = 3;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>int32 userId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->userId = $var;

        return $this;
    }

}

