<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ChannelDataService.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 *return (e.prototype = Object.create(u.rpc.Service.prototype)).constructor = e, e.prototype.getChannelData = function e(t, n) {
 *return this.rpcCall(e, f.Channel.ChannelDataRequest, f.Channel.ChannelDataResponse, t, n)
 *}, e.prototype.getChannelList = function e(t, n) {
 *return this.rpcCall(e, f.Channel.ChannelListRequest, f.Channel.ChannelListResponse, t, n)
 *}, e.prototype.getOnlineUsers = function e(t, n) {
 *return this.rpcCall(e, f.Channel.OnlineUsersRequest, f.Channel.OnlineUsersResponse, t, n)
 *}, e.prototype.resolveChannelName = function e(t, n) {
 *return this.rpcCall(e, f.Channel.ResolveChannelNameToIdRequest, f.Channel.ResolveChannelNameToIdResponse, t, n)
 *}, e
 *
 * Generated from protobuf message <code>ChannelDataService</code>
 */
class ChannelDataService extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\ChannelDataService::initOnce();
        parent::__construct($data);
    }

}

