<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckFlag.proto

if (false) {
    /**
     * This class is deprecated. Use CheckFlag\FlagCheckResponse instead.
     * @deprecated
     */
    class CheckFlag_FlagCheckResponse {}
}
class_exists(CheckFlag\FlagCheckResponse::class);
@trigger_error('CheckFlag_FlagCheckResponse is deprecated and will be removed in the next major release. Use CheckFlag\FlagCheckResponse instead', E_USER_DEPRECATED);

