<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckFlag.proto

if (false) {
    /**
     * This class is deprecated. Use CheckFlag\RequestFlagCheck instead.
     * @deprecated
     */
    class CheckFlag_RequestFlagCheck {}
}
class_exists(CheckFlag\RequestFlagCheck::class);
@trigger_error('CheckFlag_RequestFlagCheck is deprecated and will be removed in the next major release. Use CheckFlag\RequestFlagCheck instead', E_USER_DEPRECATED);

