<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CheckFlag.proto

if (false) {
    /**
     * This class is deprecated. Use CheckFlag\Flag instead.
     * @deprecated
     */
    class CheckFlag_Flag {}
}
class_exists(CheckFlag\Flag::class);
@trigger_error('CheckFlag_Flag is deprecated and will be removed in the next major release. Use CheckFlag\Flag instead', E_USER_DEPRECATED);

