<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ConnectRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ConnectRequest</code>
 */
class ConnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool wasAlreadyConnected = 1;</code>
     */
    private $wasAlreadyConnected = false;
    /**
     * Generated from protobuf field <code>bytes connectionId = 2;</code>
     */
    private $connectionId = '';
    /**
     * Generated from protobuf field <code>bool isOldProtocol = 3;</code>
     */
    private $isOldProtocol = false;
    /**
     * Generated from protobuf field <code>bool dontCreateGatewayConnection = 4;</code>
     */
    private $dontCreateGatewayConnection = false;
    /**
     * Generated from protobuf field <code>.ClientType clientType = 5;</code>
     */
    private $clientType = 0;
    /**
     * Generated from protobuf field <code>.ConnectionType connectionType = 6;</code>
     */
    private $connectionType = 0;
    /**
     * Generated from protobuf field <code>string clientVersion = 7;</code>
     */
    private $clientVersion = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $wasAlreadyConnected
     *     @type string $connectionId
     *     @type bool $isOldProtocol
     *     @type bool $dontCreateGatewayConnection
     *     @type int $clientType
     *     @type int $connectionType
     *     @type string $clientVersion
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\ConnectRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool wasAlreadyConnected = 1;</code>
     * @return bool
     */
    public function getWasAlreadyConnected()
    {
        return $this->wasAlreadyConnected;
    }

    /**
     * Generated from protobuf field <code>bool wasAlreadyConnected = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setWasAlreadyConnected($var)
    {
        GPBUtil::checkBool($var);
        $this->wasAlreadyConnected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes connectionId = 2;</code>
     * @return string
     */
    public function getConnectionId()
    {
        return $this->connectionId;
    }

    /**
     * Generated from protobuf field <code>bytes connectionId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConnectionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->connectionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isOldProtocol = 3;</code>
     * @return bool
     */
    public function getIsOldProtocol()
    {
        return $this->isOldProtocol;
    }

    /**
     * Generated from protobuf field <code>bool isOldProtocol = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOldProtocol($var)
    {
        GPBUtil::checkBool($var);
        $this->isOldProtocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool dontCreateGatewayConnection = 4;</code>
     * @return bool
     */
    public function getDontCreateGatewayConnection()
    {
        return $this->dontCreateGatewayConnection;
    }

    /**
     * Generated from protobuf field <code>bool dontCreateGatewayConnection = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDontCreateGatewayConnection($var)
    {
        GPBUtil::checkBool($var);
        $this->dontCreateGatewayConnection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ClientType clientType = 5;</code>
     * @return int
     */
    public function getClientType()
    {
        return $this->clientType;
    }

    /**
     * Generated from protobuf field <code>.ClientType clientType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setClientType($var)
    {
        GPBUtil::checkEnum($var, \ClientType::class);
        $this->clientType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ConnectionType connectionType = 6;</code>
     * @return int
     */
    public function getConnectionType()
    {
        return $this->connectionType;
    }

    /**
     * Generated from protobuf field <code>.ConnectionType connectionType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setConnectionType($var)
    {
        GPBUtil::checkEnum($var, \ConnectionType::class);
        $this->connectionType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientVersion = 7;</code>
     * @return string
     */
    public function getClientVersion()
    {
        return $this->clientVersion;
    }

    /**
     * Generated from protobuf field <code>string clientVersion = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClientVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientVersion = $var;

        return $this;
    }

}

