<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ConnectionType.proto

/**
 * Protobuf type <code>ConnectionType</code>
 */
class ConnectionType
{
    /**
     * Generated from protobuf enum <code>NotSet = 0;</code>
     */
    const NotSet = 0;
    /**
     * Generated from protobuf enum <code>Legacy = 1;</code>
     */
    const Legacy = 1;
    /**
     * Generated from protobuf enum <code>K3 = 2;</code>
     */
    const K3 = 2;

    private static $valueToName = [
        self::NotSet => 'NotSet',
        self::Legacy => 'Legacy',
        self::K3 => 'K3',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

