<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ConnectionAuthenticationStateUpdated.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ConnectionAuthenticationStateUpdated</code>
 */
class ConnectionAuthenticationStateUpdated extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool authenticated = 1;</code>
     */
    private $authenticated = false;
    /**
     * Generated from protobuf field <code>string reason = 2;</code>
     */
    private $reason = '';
    /**
     * Generated from protobuf field <code>int32 userID = 3;</code>
     */
    private $userID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $authenticated
     *     @type string $reason
     *     @type int $userID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\ConnectionAuthenticationStateUpdated::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool authenticated = 1;</code>
     * @return bool
     */
    public function getAuthenticated()
    {
        return $this->authenticated;
    }

    /**
     * Generated from protobuf field <code>bool authenticated = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAuthenticated($var)
    {
        GPBUtil::checkBool($var);
        $this->authenticated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 2;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 userID = 3;</code>
     * @return int
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     * Generated from protobuf field <code>int32 userID = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserID($var)
    {
        GPBUtil::checkInt32($var);
        $this->userID = $var;

        return $this;
    }

}

