<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/ConnectResponse.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ConnectResponse</code>
 */
class ConnectResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes connectionId = 1;</code>
     */
    private $connectionId = '';
    /**
     * Generated from protobuf field <code>bool badConnectionId = 2;</code>
     */
    private $badConnectionId = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $connectionId
     *     @type bool $badConnectionId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\ConnectResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes connectionId = 1;</code>
     * @return string
     */
    public function getConnectionId()
    {
        return $this->connectionId;
    }

    /**
     * Generated from protobuf field <code>bytes connectionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConnectionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->connectionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool badConnectionId = 2;</code>
     * @return bool
     */
    public function getBadConnectionId()
    {
        return $this->badConnectionId;
    }

    /**
     * Generated from protobuf field <code>bool badConnectionId = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBadConnectionId($var)
    {
        GPBUtil::checkBool($var);
        $this->badConnectionId = $var;

        return $this;
    }

}

