<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ConversationSnapStatus.proto

/**
 * Protobuf type <code>ConversationSnapStatus</code>
 */
class ConversationSnapStatus
{
    /**
     * Generated from protobuf enum <code>NotAvailable = 0;</code>
     */
    const NotAvailable = 0;
    /**
     * Generated from protobuf enum <code>Undecided = 1;</code>
     */
    const Undecided = 1;
    /**
     * Generated from protobuf enum <code>Yes = 2;</code>
     */
    const Yes = 2;
    /**
     * Generated from protobuf enum <code>No = 3;</code>
     */
    const No = 3;
    /**
     * Generated from protobuf enum <code>FirstTry = -1;</code>
     */
    const FirstTry = -1;
    /**
     * Generated from protobuf enum <code>SecondTry = -2;</code>
     */
    const SecondTry = -2;

    private static $valueToName = [
        self::NotAvailable => 'NotAvailable',
        self::Undecided => 'Undecided',
        self::Yes => 'Yes',
        self::No => 'No',
        self::FirstTry => 'FirstTry',
        self::SecondTry => 'SecondTry',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

