<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/Conversation.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>Conversation</code>
 */
class Conversation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool updateReadTimestamp = 1;</code>
     */
    private $updateReadTimestamp = false;
    /**
     * Generated from protobuf field <code>repeated int32 participants = 2;</code>
     */
    private $participants;
    /**
     * Generated from protobuf field <code>repeated .ConversationMessage messages = 3;</code>
     */
    private $messages;
    /**
     * Generated from protobuf field <code>int64 archiveIndex = 4;</code>
     */
    private $archiveIndex = 0;
    /**
     * Generated from protobuf field <code>int64 deleteIndex = 5;</code>
     */
    private $deleteIndex = 0;
    /**
     * Generated from protobuf field <code>int64 lastReadIndex = 6;</code>
     */
    private $lastReadIndex = 0;
    /**
     * Generated from protobuf field <code>int64 conversationId = 7;</code>
     */
    private $conversationId = 0;
    /**
     * Generated from protobuf field <code>int32 unreadMessageCount = 8;</code>
     */
    private $unreadMessageCount = 0;
    /**
     * Enum
     *
     * Generated from protobuf field <code>int32 snapStatus = 9;</code>
     */
    private $snapStatus = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $updateReadTimestamp
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $participants
     *     @type \ConversationMessage[]|\Google\Protobuf\Internal\RepeatedField $messages
     *     @type int|string $archiveIndex
     *     @type int|string $deleteIndex
     *     @type int|string $lastReadIndex
     *     @type int|string $conversationId
     *     @type int $unreadMessageCount
     *     @type int $snapStatus
     *           Enum
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool updateReadTimestamp = 1;</code>
     * @return bool
     */
    public function getUpdateReadTimestamp()
    {
        return $this->updateReadTimestamp;
    }

    /**
     * Generated from protobuf field <code>bool updateReadTimestamp = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setUpdateReadTimestamp($var)
    {
        GPBUtil::checkBool($var);
        $this->updateReadTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 participants = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParticipants()
    {
        return $this->participants;
    }

    /**
     * Generated from protobuf field <code>repeated int32 participants = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParticipants($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->participants = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ConversationMessage messages = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Generated from protobuf field <code>repeated .ConversationMessage messages = 3;</code>
     * @param \ConversationMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ConversationMessage::class);
        $this->messages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 archiveIndex = 4;</code>
     * @return int|string
     */
    public function getArchiveIndex()
    {
        return $this->archiveIndex;
    }

    /**
     * Generated from protobuf field <code>int64 archiveIndex = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setArchiveIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->archiveIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 deleteIndex = 5;</code>
     * @return int|string
     */
    public function getDeleteIndex()
    {
        return $this->deleteIndex;
    }

    /**
     * Generated from protobuf field <code>int64 deleteIndex = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeleteIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleteIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 lastReadIndex = 6;</code>
     * @return int|string
     */
    public function getLastReadIndex()
    {
        return $this->lastReadIndex;
    }

    /**
     * Generated from protobuf field <code>int64 lastReadIndex = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastReadIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->lastReadIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 7;</code>
     * @return int|string
     */
    public function getConversationId()
    {
        return $this->conversationId;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConversationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->conversationId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unreadMessageCount = 8;</code>
     * @return int
     */
    public function getUnreadMessageCount()
    {
        return $this->unreadMessageCount;
    }

    /**
     * Generated from protobuf field <code>int32 unreadMessageCount = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setUnreadMessageCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->unreadMessageCount = $var;

        return $this;
    }

    /**
     * Enum
     *
     * Generated from protobuf field <code>int32 snapStatus = 9;</code>
     * @return int
     */
    public function getSnapStatus()
    {
        return $this->snapStatus;
    }

    /**
     * Enum
     *
     * Generated from protobuf field <code>int32 snapStatus = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setSnapStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->snapStatus = $var;

        return $this;
    }

}

