<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ConversationMessage.proto

if (false) {
    /**
     * This class is deprecated. Use ConversationMessage\NestedMessage instead.
     * @deprecated
     */
    class ConversationMessage_NestedMessage {}
}
class_exists(ConversationMessage\NestedMessage::class);
@trigger_error('ConversationMessage_NestedMessage is deprecated and will be removed in the next major release. Use ConversationMessage\NestedMessage instead', E_USER_DEPRECATED);

