<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ConversationMessage.proto

if (false) {
    /**
     * This class is deprecated. Use ConversationMessage\NestedMessage\NestedMessageType instead.
     * @deprecated
     */
    class ConversationMessage_NestedMessage_NestedMessageType {}
}
class_exists(ConversationMessage\NestedMessage\NestedMessageType::class);
@trigger_error('ConversationMessage_NestedMessage_NestedMessageType is deprecated and will be removed in the next major release. Use ConversationMessage\NestedMessage\NestedMessageType instead', E_USER_DEPRECATED);

