<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/CreateDeviceTokenWebRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>CreateDeviceTokenWebRequest</code>
 */
class CreateDeviceTokenWebRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Credentials credentials = 1;</code>
     */
    private $credentials = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Credentials $credentials
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Login\CreateDeviceTokenWebRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Credentials credentials = 1;</code>
     * @return \Credentials
     */
    public function getCredentials()
    {
        return $this->credentials;
    }

    /**
     * Generated from protobuf field <code>.Credentials credentials = 1;</code>
     * @param \Credentials $var
     * @return $this
     */
    public function setCredentials($var)
    {
        GPBUtil::checkMessage($var, \Credentials::class);
        $this->credentials = $var;

        return $this;
    }

}

