<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/DisconnectedByLegacyClientConnectEvent.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>DisconnectedByLegacyClientConnectEvent</code>
 */
class DisconnectedByLegacyClientConnectEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 userId = 1;</code>
     */
    private $userId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $userId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\DisconnectedByLegacyClientConnectEvent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 userId = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>uint64 userId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->userId = $var;

        return $this;
    }

}

