<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/DisconnectRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>DisconnectRequest</code>
 */
class DisconnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string reason = 1;</code>
     */
    private $reason = '';
    /**
     * Generated from protobuf field <code>bool maybeFallback = 2;</code>
     */
    private $maybeFallback = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reason
     *     @type bool $maybeFallback
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\DisconnectRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string reason = 1;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool maybeFallback = 2;</code>
     * @return bool
     */
    public function getMaybeFallback()
    {
        return $this->maybeFallback;
    }

    /**
     * Generated from protobuf field <code>bool maybeFallback = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setMaybeFallback($var)
    {
        GPBUtil::checkBool($var);
        $this->maybeFallback = $var;

        return $this;
    }

}

