<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/FormattedText.proto

if (false) {
    /**
     * This class is deprecated. Use FormattedText\Link instead.
     * @deprecated
     */
    class FormattedText_Link {}
}
class_exists(FormattedText\Link::class);
@trigger_error('FormattedText_Link is deprecated and will be removed in the next major release. Use FormattedText\Link instead', E_USER_DEPRECATED);

