<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/FormattedText.proto

if (false) {
    /**
     * This class is deprecated. Use FormattedText\Text instead.
     * @deprecated
     */
    class FormattedText_Text {}
}
class_exists(FormattedText\Text::class);
@trigger_error('FormattedText_Text is deprecated and will be removed in the next major release. Use FormattedText\Text instead', E_USER_DEPRECATED);

