<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/FormattedText.proto

if (false) {
    /**
     * This class is deprecated. Use FormattedText\Smiley instead.
     * @deprecated
     */
    class FormattedText_Smiley {}
}
class_exists(FormattedText\Smiley::class);
@trigger_error('FormattedText_Smiley is deprecated and will be removed in the next major release. Use FormattedText\Smiley instead', E_USER_DEPRECATED);

