<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/FormattedText.proto

if (false) {
    /**
     * This class is deprecated. Use FormattedText\PBList instead.
     * @deprecated
     */
    class FormattedText_List {}
}
class_exists(FormattedText\PBList::class);
@trigger_error('FormattedText_List is deprecated and will be removed in the next major release. Use FormattedText\PBList instead', E_USER_DEPRECATED);

