<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ForwardMessageStatusResponse.proto

if (false) {
    /**
     * This class is deprecated. Use ForwardMessageStatusResponse\Status instead.
     * @deprecated
     */
    class ForwardMessageStatusResponse_Status {}
}
class_exists(ForwardMessageStatusResponse\Status::class);
@trigger_error('ForwardMessageStatusResponse_Status is deprecated and will be removed in the next major release. Use ForwardMessageStatusResponse\Status instead', E_USER_DEPRECATED);

