<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/IgnoreListComplete.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>IgnoreListComplete</code>
 */
class IgnoreListComplete extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 ignores = 1;</code>
     */
    private $ignores;
    /**
     * Generated from protobuf field <code>repeated int32 blocks = 2;</code>
     */
    private $blocks;
    /**
     * Generated from protobuf field <code>repeated int32 privateIgnores = 3;</code>
     */
    private $privateIgnores;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $ignores
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $blocks
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $privateIgnores
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserData\IgnoreListComplete::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 ignores = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIgnores()
    {
        return $this->ignores;
    }

    /**
     * Generated from protobuf field <code>repeated int32 ignores = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIgnores($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->ignores = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 blocks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlocks()
    {
        return $this->blocks;
    }

    /**
     * Generated from protobuf field <code>repeated int32 blocks = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->blocks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 privateIgnores = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrivateIgnores()
    {
        return $this->privateIgnores;
    }

    /**
     * Generated from protobuf field <code>repeated int32 privateIgnores = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrivateIgnores($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->privateIgnores = $arr;

        return $this;
    }

}

