<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/IgnoreStateAction.proto

/**
 * Protobuf type <code>IgnoreStateAction</code>
 */
class IgnoreStateAction
{
    /**
     * Generated from protobuf enum <code>IGNORE = 0;</code>
     */
    const IGNORE = 0;
    /**
     * Generated from protobuf enum <code>UNIGNORE = 1;</code>
     */
    const UNIGNORE = 1;
    /**
     * Generated from protobuf enum <code>BLOCK = 2;</code>
     */
    const BLOCK = 2;
    /**
     * Generated from protobuf enum <code>UNBLOCK = 3;</code>
     */
    const UNBLOCK = 3;
    /**
     * Generated from protobuf enum <code>ADD_PRIVATE_IGNORE = 4;</code>
     */
    const ADD_PRIVATE_IGNORE = 4;
    /**
     * Generated from protobuf enum <code>REMOVE_PRIVATE_IGNORE = 5;</code>
     */
    const REMOVE_PRIVATE_IGNORE = 5;

    private static $valueToName = [
        self::IGNORE => 'IGNORE',
        self::UNIGNORE => 'UNIGNORE',
        self::BLOCK => 'BLOCK',
        self::UNBLOCK => 'UNBLOCK',
        self::ADD_PRIVATE_IGNORE => 'ADD_PRIVATE_IGNORE',
        self::REMOVE_PRIVATE_IGNORE => 'REMOVE_PRIVATE_IGNORE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

