<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/IgnoreListUpdate.proto

if (false) {
    /**
     * This class is deprecated. Use IgnoreListUpdate\Action instead.
     * @deprecated
     */
    class IgnoreListUpdate_Action {}
}
class_exists(IgnoreListUpdate\Action::class);
@trigger_error('IgnoreListUpdate_Action is deprecated and will be removed in the next major release. Use IgnoreListUpdate\Action instead', E_USER_DEPRECATED);

