<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/InitialChannelJoin.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>InitialChannelJoin</code>
 */
class InitialChannelJoin extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\InitialChannelJoin::initOnce();
        parent::__construct($data);
    }

}

