<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/InitiatePasswordResetWebResult.proto

/**
 * Protobuf type <code>InitiatePasswordResetWebResult</code>
 */
class InitiatePasswordResetWebResult
{
    /**
     * Generated from protobuf enum <code>InitiatePasswordReset_NotSet = 0;</code>
     */
    const InitiatePasswordReset_NotSet = 0;
    /**
     * Generated from protobuf enum <code>InitiatePasswordReset_Success = 1;</code>
     */
    const InitiatePasswordReset_Success = 1;
    /**
     * Generated from protobuf enum <code>InitiatePasswordReset_ServiceNotAvailable = 2;</code>
     */
    const InitiatePasswordReset_ServiceNotAvailable = 2;
    /**
     * Generated from protobuf enum <code>InitiatePasswordReset_NoSuchUser = 3;</code>
     */
    const InitiatePasswordReset_NoSuchUser = 3;
    /**
     * Generated from protobuf enum <code>InitiatePasswordReset_NoEmail = 4;</code>
     */
    const InitiatePasswordReset_NoEmail = 4;
    /**
     * Generated from protobuf enum <code>InitiatePasswordReset_InvalidUserStatus = 5;</code>
     */
    const InitiatePasswordReset_InvalidUserStatus = 5;

    private static $valueToName = [
        self::InitiatePasswordReset_NotSet => 'InitiatePasswordReset_NotSet',
        self::InitiatePasswordReset_Success => 'InitiatePasswordReset_Success',
        self::InitiatePasswordReset_ServiceNotAvailable => 'InitiatePasswordReset_ServiceNotAvailable',
        self::InitiatePasswordReset_NoSuchUser => 'InitiatePasswordReset_NoSuchUser',
        self::InitiatePasswordReset_NoEmail => 'InitiatePasswordReset_NoEmail',
        self::InitiatePasswordReset_InvalidUserStatus => 'InitiatePasswordReset_InvalidUserStatus',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

