<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/JoinChannel.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>JoinChannel</code>
 */
class JoinChannel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     */
    private $channelID = null;
    /**
     * Generated from protobuf field <code>bool allowSubChannel = 2;</code>
     */
    private $allowSubChannel = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $channelID
     *     @type bool $allowSubChannel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\JoinChannel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getChannelID()
    {
        return $this->channelID;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setChannelID($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->channelID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allowSubChannel = 2;</code>
     * @return bool
     */
    public function getAllowSubChannel()
    {
        return $this->allowSubChannel;
    }

    /**
     * Generated from protobuf field <code>bool allowSubChannel = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowSubChannel($var)
    {
        GPBUtil::checkBool($var);
        $this->allowSubChannel = $var;

        return $this;
    }

}

