<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/MessageStatus.proto

if (false) {
    /**
     * This class is deprecated. Use MessageStatus\Status instead.
     * @deprecated
     */
    class MessageStatus_Status {}
}
class_exists(MessageStatus\Status::class);
@trigger_error('MessageStatus_Status is deprecated and will be removed in the next major release. Use MessageStatus\Status instead', E_USER_DEPRECATED);

