<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/MessageSendError.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>MessageSendError</code>
 */
class MessageSendError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MessageSendError.ErrorType reason = 1;</code>
     */
    private $reason = 0;
    /**
     * Generated from protobuf field <code>string text = 2;</code>
     */
    private $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $reason
     *     @type string $text
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\MessageSendError::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MessageSendError.ErrorType reason = 1;</code>
     * @return int
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>.MessageSendError.ErrorType reason = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \MessageSendError_ErrorType::class);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

