<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/MessageSendError.proto

if (false) {
    /**
     * This class is deprecated. Use MessageSendError\ErrorType instead.
     * @deprecated
     */
    class MessageSendError_ErrorType {}
}
class_exists(MessageSendError\ErrorType::class);
@trigger_error('MessageSendError_ErrorType is deprecated and will be removed in the next major release. Use MessageSendError\ErrorType instead', E_USER_DEPRECATED);

