<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/MessageID.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>MessageID</code>
 */
class MessageID extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     */
    private $channelID = null;
    /**
     * Generated from protobuf field <code>int64 messageCount = 2;</code>
     */
    private $messageCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $channelID
     *     @type int|string $messageCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\MessageID::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getChannelID()
    {
        return $this->channelID;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setChannelID($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->channelID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 messageCount = 2;</code>
     * @return int|string
     */
    public function getMessageCount()
    {
        return $this->messageCount;
    }

    /**
     * Generated from protobuf field <code>int64 messageCount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->messageCount = $var;

        return $this;
    }

}

