<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/MessageInChannelServer.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>MessageInChannelServer</code>
 */
class MessageInChannelServer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     */
    private $channelID = null;
    /**
     * Generated from protobuf field <code>int32 senderID = 2;</code>
     */
    private $senderID = 0;
    /**
     * Generated from protobuf field <code>string deprecated_message = 3;</code>
     */
    private $deprecated_message = '';
    /**
     * Generated from protobuf field <code>.FormattedText message = 7;</code>
     */
    private $message = null;
    /**
     * Generated from protobuf field <code>int32 messageType = 4;</code>
     */
    private $messageType = 0;
    /**
     * Generated from protobuf field <code>.MessageID messageID = 5;</code>
     */
    private $messageID = null;
    /**
     * Generated from protobuf field <code>repeated int32 receiverID = 6;</code>
     */
    private $receiverID;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $channelID
     *     @type int $senderID
     *     @type string $deprecated_message
     *     @type \FormattedText $message
     *     @type int $messageType
     *     @type \MessageID $messageID
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $receiverID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\MessageInChannelServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getChannelID()
    {
        return $this->channelID;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setChannelID($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->channelID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 senderID = 2;</code>
     * @return int
     */
    public function getSenderID()
    {
        return $this->senderID;
    }

    /**
     * Generated from protobuf field <code>int32 senderID = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSenderID($var)
    {
        GPBUtil::checkInt32($var);
        $this->senderID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deprecated_message = 3;</code>
     * @return string
     */
    public function getDeprecatedMessage()
    {
        return $this->deprecated_message;
    }

    /**
     * Generated from protobuf field <code>string deprecated_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDeprecatedMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->deprecated_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FormattedText message = 7;</code>
     * @return \FormattedText
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>.FormattedText message = 7;</code>
     * @param \FormattedText $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \FormattedText::class);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 messageType = 4;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->messageType;
    }

    /**
     * Generated from protobuf field <code>int32 messageType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkInt32($var);
        $this->messageType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MessageID messageID = 5;</code>
     * @return \MessageID
     */
    public function getMessageID()
    {
        return $this->messageID;
    }

    /**
     * Generated from protobuf field <code>.MessageID messageID = 5;</code>
     * @param \MessageID $var
     * @return $this
     */
    public function setMessageID($var)
    {
        GPBUtil::checkMessage($var, \MessageID::class);
        $this->messageID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 receiverID = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReceiverID()
    {
        return $this->receiverID;
    }

    /**
     * Generated from protobuf field <code>repeated int32 receiverID = 6;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReceiverID($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->receiverID = $arr;

        return $this;
    }

}

