<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/NicklistUpdate.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>NicklistUpdate</code>
 */
class NicklistUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     */
    private $channelID = null;
    /**
     * Generated from protobuf field <code>int64 versionNumber = 2;</code>
     */
    private $versionNumber = 0;
    /**
     * Generated from protobuf field <code>repeated .NicklistChange change = 3;</code>
     */
    private $change;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $channelID
     *     @type int|string $versionNumber
     *     @type \NicklistChange[]|\Google\Protobuf\Internal\RepeatedField $change
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\NicklistUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getChannelID()
    {
        return $this->channelID;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelID = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setChannelID($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->channelID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 versionNumber = 2;</code>
     * @return int|string
     */
    public function getVersionNumber()
    {
        return $this->versionNumber;
    }

    /**
     * Generated from protobuf field <code>int64 versionNumber = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->versionNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .NicklistChange change = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChange()
    {
        return $this->change;
    }

    /**
     * Generated from protobuf field <code>repeated .NicklistChange change = 3;</code>
     * @param \NicklistChange[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChange($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \NicklistChange::class);
        $this->change = $arr;

        return $this;
    }

}

