<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/OnlineUsersRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>OnlineUsersRequest</code>
 */
class OnlineUsersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelId = 1;</code>
     */
    private $channelId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $channelId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\OnlineUsersRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelId = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getChannelId()
    {
        return $this->channelId;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelId = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setChannelId($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->channelId = $var;

        return $this;
    }

}

