<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/PrivateMessageServer.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>PrivateMessageServer</code>
 */
class PrivateMessageServer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 senderID = 1;</code>
     */
    private $senderID = 0;
    /**
     * Generated from protobuf field <code>repeated int32 receiverID = 2;</code>
     */
    private $receiverID;
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $senderID
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $receiverID
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\PrivateMessageServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 senderID = 1;</code>
     * @return int
     */
    public function getSenderID()
    {
        return $this->senderID;
    }

    /**
     * Generated from protobuf field <code>int32 senderID = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSenderID($var)
    {
        GPBUtil::checkInt32($var);
        $this->senderID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 receiverID = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReceiverID()
    {
        return $this->receiverID;
    }

    /**
     * Generated from protobuf field <code>repeated int32 receiverID = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReceiverID($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->receiverID = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

