<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ReadAllConversationsStatusResponse.proto

if (false) {
    /**
     * This class is deprecated. Use ReadAllConversationsStatusResponse\Status instead.
     * @deprecated
     */
    class ReadAllConversationsStatusResponse_Status {}
}
class_exists(ReadAllConversationsStatusResponse\Status::class);
@trigger_error('ReadAllConversationsStatusResponse_Status is deprecated and will be removed in the next major release. Use ReadAllConversationsStatusResponse\Status instead', E_USER_DEPRECATED);

