<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/ReadMessages.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ReadMessages</code>
 */
class ReadMessages extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 messageId = 1;</code>
     */
    private $messageId;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $messageId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\ReadMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 messageId = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessageId()
    {
        return $this->messageId;
    }

    /**
     * Generated from protobuf field <code>repeated int64 messageId = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessageId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->messageId = $arr;

        return $this;
    }

}

