<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/RegistrationRequest.proto

if (false) {
    /**
     * This class is deprecated. Use RegistrationRequest\Gender instead.
     * @deprecated
     */
    class RegistrationRequest_Gender {}
}
class_exists(RegistrationRequest\Gender::class);
@trigger_error('RegistrationRequest_Gender is deprecated and will be removed in the next major release. Use RegistrationRequest\Gender instead', E_USER_DEPRECATED);

