<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/RegistrationResponse.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>RegistrationResponse</code>
 */
class RegistrationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string oks = 1;</code>
     */
    private $oks;
    /**
     * Generated from protobuf field <code>repeated .Error errors = 2;</code>
     */
    private $errors;
    /**
     * Generated from protobuf field <code>.Success success = 3;</code>
     */
    private $success = null;
    /**
     * Generated from protobuf field <code>string nickContext = 4;</code>
     */
    private $nickContext = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $oks
     *     @type \Error[]|\Google\Protobuf\Internal\RepeatedField $errors
     *     @type \Success $success
     *     @type string $nickContext
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Registration\RegistrationResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string oks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOks()
    {
        return $this->oks;
    }

    /**
     * Generated from protobuf field <code>repeated string oks = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->oks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Error errors = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>repeated .Error errors = 2;</code>
     * @param \Error[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Error::class);
        $this->errors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Success success = 3;</code>
     * @return \Success
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>.Success success = 3;</code>
     * @param \Success $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkMessage($var, \Success::class);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickContext = 4;</code>
     * @return string
     */
    public function getNickContext()
    {
        return $this->nickContext;
    }

    /**
     * Generated from protobuf field <code>string nickContext = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNickContext($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickContext = $var;

        return $this;
    }

}

