<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/RequestStarredMessages.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>RequestStarredMessages</code>
 */
class RequestStarredMessages extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\RequestStarredMessages::initOnce();
        parent::__construct($data);
    }

}

