<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/ResolveChannelNameToIdResponse.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ResolveChannelNameToIdResponse</code>
 */
class ResolveChannelNameToIdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelId = 1;</code>
     */
    private $channelId = null;
    /**
     * Generated from protobuf field <code>int32 responseStatus = 2;</code>
     */
    private $responseStatus = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ChannelIdentifier $channelId
     *     @type int $responseStatus
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\ResolveChannelNameToIdResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelId = 1;</code>
     * @return \ChannelIdentifier
     */
    public function getChannelId()
    {
        return $this->channelId;
    }

    /**
     * Generated from protobuf field <code>.ChannelIdentifier channelId = 1;</code>
     * @param \ChannelIdentifier $var
     * @return $this
     */
    public function setChannelId($var)
    {
        GPBUtil::checkMessage($var, \ChannelIdentifier::class);
        $this->channelId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 responseStatus = 2;</code>
     * @return int
     */
    public function getResponseStatus()
    {
        return $this->responseStatus;
    }

    /**
     * Generated from protobuf field <code>int32 responseStatus = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResponseStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->responseStatus = $var;

        return $this;
    }

}

