<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SendTyping.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>SendTyping</code>
 */
class SendTyping extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 receivers = 1;</code>
     */
    private $receivers;
    /**
     * Generated from protobuf field <code>int64 conversationId = 2;</code>
     */
    private $conversationId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $receivers
     *     @type int|string $conversationId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\SendTyping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 receivers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReceivers()
    {
        return $this->receivers;
    }

    /**
     * Generated from protobuf field <code>repeated int32 receivers = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReceivers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->receivers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 2;</code>
     * @return int|string
     */
    public function getConversationId()
    {
        return $this->conversationId;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConversationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->conversationId = $var;

        return $this;
    }

}

