<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SendMessageStatusResponse.proto

if (false) {
    /**
     * This class is deprecated. Use SendMessageStatusResponse\Status instead.
     * @deprecated
     */
    class SendMessageStatusResponse_Status {}
}
class_exists(SendMessageStatusResponse\Status::class);
@trigger_error('SendMessageStatusResponse_Status is deprecated and will be removed in the next major release. Use SendMessageStatusResponse\Status instead', E_USER_DEPRECATED);

