<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SetClientSettingsRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>SetClientSettingsRequest</code>
 */
class SetClientSettingsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ClientSettings settings = 1;</code>
     */
    private $settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \ClientSettings $settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\SetClientSettingsRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ClientSettings settings = 1;</code>
     * @return \ClientSettings
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * Generated from protobuf field <code>.ClientSettings settings = 1;</code>
     * @param \ClientSettings $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \ClientSettings::class);
        $this->settings = $var;

        return $this;
    }

}

