<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/SetPasswordCredentialsWebRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>SetPasswordCredentialsWebRequest</code>
 */
class SetPasswordCredentialsWebRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 deprecated1 = 1;</code>
     */
    private $deprecated1 = 0;
    /**
     * Generated from protobuf field <code>int32 deprecated2 = 2;</code>
     */
    private $deprecated2 = 0;
    /**
     * Generated from protobuf field <code>string authToken = 3;</code>
     */
    private $authToken = '';
    /**
     * Generated from protobuf field <code>string plaintextPassword = 4;</code>
     */
    private $plaintextPassword = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $deprecated1
     *     @type int $deprecated2
     *     @type string $authToken
     *     @type string $plaintextPassword
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Login\SetPasswordCredentialsWebRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 deprecated1 = 1;</code>
     * @return int
     */
    public function getDeprecated1()
    {
        return $this->deprecated1;
    }

    /**
     * Generated from protobuf field <code>int32 deprecated1 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDeprecated1($var)
    {
        GPBUtil::checkInt32($var);
        $this->deprecated1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 deprecated2 = 2;</code>
     * @return int
     */
    public function getDeprecated2()
    {
        return $this->deprecated2;
    }

    /**
     * Generated from protobuf field <code>int32 deprecated2 = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDeprecated2($var)
    {
        GPBUtil::checkInt32($var);
        $this->deprecated2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string authToken = 3;</code>
     * @return string
     */
    public function getAuthToken()
    {
        return $this->authToken;
    }

    /**
     * Generated from protobuf field <code>string authToken = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->authToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plaintextPassword = 4;</code>
     * @return string
     */
    public function getPlaintextPassword()
    {
        return $this->plaintextPassword;
    }

    /**
     * Generated from protobuf field <code>string plaintextPassword = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaintextPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->plaintextPassword = $var;

        return $this;
    }

}

