<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SetSnapsAllowed.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>SetSnapsAllowed</code>
 */
class SetSnapsAllowed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     */
    private $userId = 0;
    /**
     * Generated from protobuf field <code>bool allowed = 2;</code>
     */
    private $allowed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $userId
     *     @type bool $allowed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\SetSnapsAllowed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allowed = 2;</code>
     * @return bool
     */
    public function getAllowed()
    {
        return $this->allowed;
    }

    /**
     * Generated from protobuf field <code>bool allowed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowed($var)
    {
        GPBUtil::checkBool($var);
        $this->allowed = $var;

        return $this;
    }

}

