<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/SetTyping.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>SetTyping</code>
 */
class SetTyping extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     */
    private $userId = 0;
    /**
     * Generated from protobuf field <code>repeated int32 participants = 2;</code>
     */
    private $participants;
    /**
     * Generated from protobuf field <code>int64 conversationId = 3;</code>
     */
    private $conversationId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $userId
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $participants
     *     @type int|string $conversationId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\SetTyping::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 participants = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParticipants()
    {
        return $this->participants;
    }

    /**
     * Generated from protobuf field <code>repeated int32 participants = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParticipants($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->participants = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 3;</code>
     * @return int|string
     */
    public function getConversationId()
    {
        return $this->conversationId;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConversationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->conversationId = $var;

        return $this;
    }

}

