<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/TokenPayload.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>TokenPayload</code>
 */
class TokenPayload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>int64 userId = 2;</code>
     */
    private $userId = 0;
    /**
     * Generated from protobuf field <code>.DeviceTokenData deviceTokenData = 3;</code>
     */
    private $deviceTokenData = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int|string $userId
     *     @type \DeviceTokenData $deviceTokenData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Login\TokenPayload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 userId = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>int64 userId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DeviceTokenData deviceTokenData = 3;</code>
     * @return \DeviceTokenData
     */
    public function getDeviceTokenData()
    {
        return $this->deviceTokenData;
    }

    /**
     * Generated from protobuf field <code>.DeviceTokenData deviceTokenData = 3;</code>
     * @param \DeviceTokenData $var
     * @return $this
     */
    public function setDeviceTokenData($var)
    {
        GPBUtil::checkMessage($var, \DeviceTokenData::class);
        $this->deviceTokenData = $var;

        return $this;
    }

}

