<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/TokenRequestResult.proto

/**
 * Protobuf type <code>TokenRequestResult</code>
 */
class TokenRequestResult
{
    /**
     * Generated from protobuf enum <code>TokenRequestResult_NotSet = 0;</code>
     */
    const TokenRequestResult_NotSet = 0;
    /**
     * Generated from protobuf enum <code>TokenRequestResult_Success = 1;</code>
     */
    const TokenRequestResult_Success = 1;
    /**
     * Generated from protobuf enum <code>TokenRequestResult_UserUnknown = 2;</code>
     */
    const TokenRequestResult_UserUnknown = 2;
    /**
     * Generated from protobuf enum <code>TokenRequestResult_InvalidCredentials = 3;</code>
     */
    const TokenRequestResult_InvalidCredentials = 3;
    /**
     * Generated from protobuf enum <code>TokenRequestResult_InternalError = 4;</code>
     */
    const TokenRequestResult_InternalError = 4;

    private static $valueToName = [
        self::TokenRequestResult_NotSet => 'TokenRequestResult_NotSet',
        self::TokenRequestResult_Success => 'TokenRequestResult_Success',
        self::TokenRequestResult_UserUnknown => 'TokenRequestResult_UserUnknown',
        self::TokenRequestResult_InvalidCredentials => 'TokenRequestResult_InvalidCredentials',
        self::TokenRequestResult_InternalError => 'TokenRequestResult_InternalError',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

