<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UpdateInContactEndTimeResponse.proto

if (false) {
    /**
     * This class is deprecated. Use UpdateInContactEndTimeResponse\Status instead.
     * @deprecated
     */
    class UpdateInContactEndTimeResponse_Status {}
}
class_exists(UpdateInContactEndTimeResponse\Status::class);
@trigger_error('UpdateInContactEndTimeResponse_Status is deprecated and will be removed in the next major release. Use UpdateInContactEndTimeResponse\Status instead', E_USER_DEPRECATED);

