<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UpdateInContactEndTimeRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>UpdateInContactEndTimeRequest</code>
 */
class UpdateInContactEndTimeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 senderId = 1;</code>
     */
    private $senderId = 0;
    /**
     * Generated from protobuf field <code>int32 receiverId = 2;</code>
     */
    private $receiverId = 0;
    /**
     * Generated from protobuf field <code>int64 endTimestamp = 3;</code>
     */
    private $endTimestamp = 0;
    /**
     * Generated from protobuf field <code>.UpdateInContactEndTimeRequest.Status updateStatus = 4;</code>
     */
    private $updateStatus = 0;
    /**
     * Generated from protobuf field <code>bool statusValue = 5;</code>
     */
    private $statusValue = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $senderId
     *     @type int $receiverId
     *     @type int|string $endTimestamp
     *     @type int $updateStatus
     *     @type bool $statusValue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\UpdateInContactEndTimeRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 senderId = 1;</code>
     * @return int
     */
    public function getSenderId()
    {
        return $this->senderId;
    }

    /**
     * Generated from protobuf field <code>int32 senderId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSenderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->senderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 receiverId = 2;</code>
     * @return int
     */
    public function getReceiverId()
    {
        return $this->receiverId;
    }

    /**
     * Generated from protobuf field <code>int32 receiverId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setReceiverId($var)
    {
        GPBUtil::checkInt32($var);
        $this->receiverId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 endTimestamp = 3;</code>
     * @return int|string
     */
    public function getEndTimestamp()
    {
        return $this->endTimestamp;
    }

    /**
     * Generated from protobuf field <code>int64 endTimestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->endTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.UpdateInContactEndTimeRequest.Status updateStatus = 4;</code>
     * @return int
     */
    public function getUpdateStatus()
    {
        return $this->updateStatus;
    }

    /**
     * Generated from protobuf field <code>.UpdateInContactEndTimeRequest.Status updateStatus = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateStatus($var)
    {
        GPBUtil::checkEnum($var, \UpdateInContactEndTimeRequest_Status::class);
        $this->updateStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool statusValue = 5;</code>
     * @return bool
     */
    public function getStatusValue()
    {
        return $this->statusValue;
    }

    /**
     * Generated from protobuf field <code>bool statusValue = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatusValue($var)
    {
        GPBUtil::checkBool($var);
        $this->statusValue = $var;

        return $this;
    }

}

