<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UpdateConversationArchiveState.proto

if (false) {
    /**
     * This class is deprecated. Use UpdateConversationArchiveState\State instead.
     * @deprecated
     */
    class UpdateConversationArchiveState_State {}
}
class_exists(UpdateConversationArchiveState\State::class);
@trigger_error('UpdateConversationArchiveState_State is deprecated and will be removed in the next major release. Use UpdateConversationArchiveState\State instead', E_USER_DEPRECATED);

