<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UpdateConversationArchiveState.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>UpdateConversationArchiveState</code>
 */
class UpdateConversationArchiveState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 conversationId = 1;</code>
     */
    private $conversationId = 0;
    /**
     * Generated from protobuf field <code>.UpdateConversationArchiveState.State state = 2;</code>
     */
    private $state = 0;
    /**
     * Generated from protobuf field <code>int64 messageId = 3;</code>
     */
    private $messageId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $conversationId
     *     @type int $state
     *     @type int|string $messageId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Messenger\UpdateConversationArchiveState::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 1;</code>
     * @return int|string
     */
    public function getConversationId()
    {
        return $this->conversationId;
    }

    /**
     * Generated from protobuf field <code>int64 conversationId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConversationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->conversationId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.UpdateConversationArchiveState.State state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.UpdateConversationArchiveState.State state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \UpdateConversationArchiveState_State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 messageId = 3;</code>
     * @return int|string
     */
    public function getMessageId()
    {
        return $this->messageId;
    }

    /**
     * Generated from protobuf field <code>int64 messageId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkInt64($var);
        $this->messageId = $var;

        return $this;
    }

}

