<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messenger/UpdateInContactEndTimeRequest.proto

if (false) {
    /**
     * This class is deprecated. Use UpdateInContactEndTimeRequest\Status instead.
     * @deprecated
     */
    class UpdateInContactEndTimeRequest_Status {}
}
class_exists(UpdateInContactEndTimeRequest\Status::class);
@trigger_error('UpdateInContactEndTimeRequest_Status is deprecated and will be removed in the next major release. Use UpdateInContactEndTimeRequest\Status instead', E_USER_DEPRECATED);

