<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/UserDataByNickRequest.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>UserDataByNickRequest</code>
 */
class UserDataByNickRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string nick = 1;</code>
     */
    private $nick = '';
    /**
     * Generated from protobuf field <code>repeated int32 fields = 2;</code>
     */
    private $fields;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $nick
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $fields
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserData\UserDataByNickRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string nick = 1;</code>
     * @return string
     */
    public function getNick()
    {
        return $this->nick;
    }

    /**
     * Generated from protobuf field <code>string nick = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNick($var)
    {
        GPBUtil::checkString($var, True);
        $this->nick = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 fields = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated int32 fields = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->fields = $arr;

        return $this;
    }

}

