<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/UserData.proto

if (false) {
    /**
     * This class is deprecated. Use UserData\AccountType instead.
     * @deprecated
     */
    class UserData_AccountType {}
}
class_exists(UserData\AccountType::class);
@trigger_error('UserData_AccountType is deprecated and will be removed in the next major release. Use UserData\AccountType instead', E_USER_DEPRECATED);

