<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Channel/UserNicklistData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>UserNicklistData</code>
 */
class UserNicklistData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 userID = 1;</code>
     */
    private $userID = 0;
    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     */
    private $nickname = '';
    /**
     * Generated from protobuf field <code>int64 joinTimestamp = 3;</code>
     */
    private $joinTimestamp = 0;
    /**
     * Generated from protobuf field <code>int32 age = 4;</code>
     */
    private $age = 0;
    /**
     * Gender-Enum?
     *
     * Generated from protobuf field <code>int32 gender = 5;</code>
     */
    private $gender = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $userID
     *     @type string $nickname
     *     @type int|string $joinTimestamp
     *     @type int $age
     *     @type int $gender
     *           Gender-Enum?
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Channel\UserNicklistData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 userID = 1;</code>
     * @return int
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     * Generated from protobuf field <code>int32 userID = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserID($var)
    {
        GPBUtil::checkInt32($var);
        $this->userID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 joinTimestamp = 3;</code>
     * @return int|string
     */
    public function getJoinTimestamp()
    {
        return $this->joinTimestamp;
    }

    /**
     * Generated from protobuf field <code>int64 joinTimestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJoinTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->joinTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 age = 4;</code>
     * @return int
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * Generated from protobuf field <code>int32 age = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;

        return $this;
    }

    /**
     * Gender-Enum?
     *
     * Generated from protobuf field <code>int32 gender = 5;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Gender-Enum?
     *
     * Generated from protobuf field <code>int32 gender = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkInt32($var);
        $this->gender = $var;

        return $this;
    }

}

