<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/UserData.proto

if (false) {
    /**
     * This class is deprecated. Use UserData\BotInfo instead.
     * @deprecated
     */
    class UserData_BotInfo {}
}
class_exists(UserData\BotInfo::class);
@trigger_error('UserData_BotInfo is deprecated and will be removed in the next major release. Use UserData\BotInfo instead', E_USER_DEPRECATED);

