<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData/Userfield.proto

/**
 * Protobuf type <code>Userfield</code>
 */
class Userfield
{
    /**
     * Generated from protobuf enum <code>Nickname = 0;</code>
     */
    const Nickname = 0;
    /**
     * Generated from protobuf enum <code>Age = 1;</code>
     */
    const Age = 1;
    /**
     * Generated from protobuf enum <code>Gender = 2;</code>
     */
    const Gender = 2;
    /**
     * Generated from protobuf enum <code>ReadMe = 3;</code>
     */
    const ReadMe = 3;
    /**
     * Generated from protobuf enum <code>Distance = 4;</code>
     */
    const Distance = 4;
    /**
     * Generated from protobuf enum <code>OnlineStatus = 5;</code>
     */
    const OnlineStatus = 5;
    /**
     * Generated from protobuf enum <code>Channel = 6;</code>
     */
    const Channel = 6;
    /**
     * Generated from protobuf enum <code>IsIgnoring = 7;</code>
     */
    const IsIgnoring = 7;
    /**
     * Generated from protobuf enum <code>IsAdFree = 8;</code>
     */
    const IsAdFree = 8;
    /**
     * Generated from protobuf enum <code>AccountType = 9;</code>
     */
    const AccountType = 9;
    /**
     * Generated from protobuf enum <code>BotInfo = 10;</code>
     */
    const BotInfo = 10;

    private static $valueToName = [
        self::Nickname => 'Nickname',
        self::Age => 'Age',
        self::Gender => 'Gender',
        self::ReadMe => 'ReadMe',
        self::Distance => 'Distance',
        self::OnlineStatus => 'OnlineStatus',
        self::Channel => 'Channel',
        self::IsIgnoring => 'IsIgnoring',
        self::IsAdFree => 'IsAdFree',
        self::AccountType => 'AccountType',
        self::BotInfo => 'BotInfo',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

