<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/ValidateAuthTokenWebResponse.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>ValidateAuthTokenWebResponse</code>
 */
class ValidateAuthTokenWebResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>.TokenPayload tokenData = 2;</code>
     */
    private $tokenData = null;
    /**
     * Generated from protobuf field <code>string username = 3;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>bool accountDisabled = 4;</code>
     */
    private $accountDisabled = false;
    /**
     * Generated from protobuf field <code>string disableReason = 5;</code>
     */
    private $disableReason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result
     *     @type \TokenPayload $tokenData
     *     @type string $username
     *     @type bool $accountDisabled
     *     @type string $disableReason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Login\ValidateAuthTokenWebResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>int32 result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkInt32($var);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TokenPayload tokenData = 2;</code>
     * @return \TokenPayload
     */
    public function getTokenData()
    {
        return $this->tokenData;
    }

    /**
     * Generated from protobuf field <code>.TokenPayload tokenData = 2;</code>
     * @param \TokenPayload $var
     * @return $this
     */
    public function setTokenData($var)
    {
        GPBUtil::checkMessage($var, \TokenPayload::class);
        $this->tokenData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accountDisabled = 4;</code>
     * @return bool
     */
    public function getAccountDisabled()
    {
        return $this->accountDisabled;
    }

    /**
     * Generated from protobuf field <code>bool accountDisabled = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAccountDisabled($var)
    {
        GPBUtil::checkBool($var);
        $this->accountDisabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string disableReason = 5;</code>
     * @return string
     */
    public function getDisableReason()
    {
        return $this->disableReason;
    }

    /**
     * Generated from protobuf field <code>string disableReason = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDisableReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->disableReason = $var;

        return $this;
    }

}

