<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/FormattedText.proto

namespace FormattedText;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>FormattedText.Smiley</code>
 */
class Smiley extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string json = 1;</code>
     */
    private $json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $json
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\FormattedText::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string json = 1;</code>
     * @return string
     */
    public function getJson()
    {
        return $this->json;
    }

    /**
     * Generated from protobuf field <code>string json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->json = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Smiley::class, \FormattedText_Smiley::class);

