<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/ErrorInfo.proto

namespace GPBMetadata\Registration;

class ErrorInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4010a1c726567697374726174696f6e2f4572726f72496e666f2e7072" .
            "6f746f120c726567697374726174696f6e2a6e0a094572726f72496e666f" .
            "120d0a096669656c644e616d651000120d0a096572726f72547970651001" .
            "12100a0c6572726f7253756254797065100212070a036d696e100312070a" .
            "036d61781004120f0a0b70726f626c656d436861721005120e0a0a637573" .
            "746f6d496e666f1006620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

