<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/ErrorInfo.proto

namespace GPBMetadata\Registration;

class ErrorInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a96010a1c726567697374726174696f6e2f4572726f72496e666f2e7072" .
            "6f746f2a6e0a094572726f72496e666f120d0a096669656c644e616d6510" .
            "00120d0a096572726f7254797065100112100a0c6572726f725375625479" .
            "7065100212070a036d696e100312070a036d61781004120f0a0b70726f62" .
            "6c656d436861721005120e0a0a637573746f6d496e666f1006620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

