<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/Error.proto

namespace GPBMetadata\Registration;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Registration\RequestType::initOnce();
        \GPBMetadata\Registration\ErrorType::initOnce();
        \GPBMetadata\Registration\ErrorInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae5010a18726567697374726174696f6e2f4572726f722e70726f746f1a" .
            "1c726567697374726174696f6e2f4572726f72547970652e70726f746f1a" .
            "1c726567697374726174696f6e2f4572726f72496e666f2e70726f746f22" .
            "84010a054572726f72121a0a046e616d6518012001280e320c2e52657175" .
            "6573745479706512130a0b73756767657374696f6e73180220032809120c" .
            "0a0474657874180320012809121d0a096572726f72547970651804200128" .
            "0e320a2e4572726f7254797065121d0a096572726f72496e666f18052001" .
            "280e320a2e4572726f72496e666f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

