<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/Error.proto

namespace GPBMetadata\Registration;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Registration\RequestType::initOnce();
        \GPBMetadata\Registration\ErrorType::initOnce();
        \GPBMetadata\Registration\ErrorInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a020a18726567697374726174696f6e2f4572726f722e70726f746f12" .
            "0c726567697374726174696f6e1a1c726567697374726174696f6e2f4572" .
            "726f72547970652e70726f746f1a1c726567697374726174696f6e2f4572" .
            "726f72496e666f2e70726f746f22ab010a054572726f7212270a046e616d" .
            "6518012001280e32192e726567697374726174696f6e2e52657175657374" .
            "5479706512130a0b73756767657374696f6e73180220032809120c0a0474" .
            "657874180320012809122a0a096572726f725479706518042001280e3217" .
            "2e726567697374726174696f6e2e4572726f7254797065122a0a09657272" .
            "6f72496e666f18052001280e32172e726567697374726174696f6e2e4572" .
            "726f72496e666f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

