<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/RegistrationResponse.proto

namespace GPBMetadata\Registration;

class RegistrationResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Registration\Error::initOnce();
        \GPBMetadata\Registration\Success::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3010a27726567697374726174696f6e2f526567697374726174696f6e" .
            "526573706f6e73652e70726f746f120c726567697374726174696f6e1a1a" .
            "726567697374726174696f6e2f537563636573732e70726f746f2285010a" .
            "14526567697374726174696f6e526573706f6e7365120b0a036f6b731801" .
            "2003280912230a066572726f727318022003280b32132e72656769737472" .
            "6174696f6e2e4572726f7212260a077375636365737318032001280b3215" .
            "2e726567697374726174696f6e2e5375636365737312130a0b6e69636b43" .
            "6f6e74657874180420012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

