<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/RegistrationResponse.proto

namespace GPBMetadata\Registration;

class RegistrationResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Registration\Error::initOnce();
        \GPBMetadata\Registration\Success::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aba010a27726567697374726174696f6e2f526567697374726174696f6e" .
            "526573706f6e73652e70726f746f1a1a726567697374726174696f6e2f53" .
            "7563636573732e70726f746f226b0a14526567697374726174696f6e5265" .
            "73706f6e7365120b0a036f6b7318012003280912160a066572726f727318" .
            "022003280b32062e4572726f7212190a077375636365737318032001280b" .
            "32082e5375636365737312130a0b6e69636b436f6e746578741804200128" .
            "09620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

