<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration/RequestType.proto

namespace GPBMetadata\Registration;

class RequestType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2010a1e726567697374726174696f6e2f52657175657374547970652e" .
            "70726f746f2a780a0b526571756573745479706512070a03414c4c100012" .
            "080a044e49434b100112070a034147451002120a0a0647454e4445521003" .
            "12090a05454d41494c1004120c0a0850415353574f5244100512070a0343" .
            "41501006120f0a0b46554c4c5f5245475f56311007120e0a0a4348415453" .
            "45525645521008620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

